### ISSUE TITLE
Remove white bars from Vimeo player

### ISSUE THREAD

**Issue by KennethSkelton** [dyc3/opentogethertube#1061]
### Is your feature request related to a problem? Please describe.

When playing a video from vimeo white bars are inserted into the player to conform the video to a specific aspect ratio. 

This can be seen when playing this video: https://vimeo.com/28941097 and in https://vimeo.com/855564854 

When the video is not wide enough, bars are inserted on the sides. when the video is too wide, bars are inserted on the top and bottom. Using the room in theater mode has no effect on this issue

### Describe the solution you'd like

Either remove the bars, or find some way to turn the bars black, or find some way to match the bars to the room color theme.

Vimeo themselves solves this issue by having an ultra wide player and filling in the space on the left and right with black.

### Additional context

Screenshot of the bars on ott

<img width="1399" alt="Screen Shot 2023-08-25 at 11 22 12 PM" src="https://github.com/dyc3/opentogethertube/assets/48537790/77012fd6-2fbb-458d-90cb-bd6cb938ee4e">

<img width="1401" alt="Screen Shot 2023-08-25 at 11 26 31 PM" src="https://github.com/dyc3/opentogethertube/assets/48537790/22773e3b-2374-4a85-89b2-23e53eedfdb9">

corrosponding videos on vimeo

<img width="1403" alt="Screen Shot 2023-08-25 at 11 26 50 PM" src="https://github.com/dyc3/opentogethertube/assets/48537790/0a6cf1da-5f92-4644-9bd2-e83e4140f156">

<img width="1411" alt="Screen Shot 2023-08-25 at 11 27 06 PM" src="https://github.com/dyc3/opentogethertube/assets/48537790/f1bcc034-268a-40af-99a7-f3726d96d12a">

**Comment by dyc3** [comment]
So apparently, if the color scheme of the parent page is different from the color scheme of the iframe page, the iframe background will become opaque. Source: https://fvsch.com/transparent-iframes

I've filed 2 upstream issues related to this:
- https://github.com/vimeo/player.js/issues/949
- https://github.com/vimeo/player.js/issues/950
