### ISSUE TITLE
Balancer: set up prometheus metrics exporter

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1094]
### Is your feature request related to a problem? Please describe.

The balancer currently doesn't have prometheus metrics set up.

### Describe the solution you'd like

Metrics should be made available at the `GET /api/status/metrics` endpoint, where the TODO is in `service.rs`.

The balancer's fly config should also be updated to collect metrics.

**Comment by cjrkoa** [comment]
I'd like to pick up this issue
