### ISSUE TITLE
Subtitles dont Seem to work on custom videos

### ISSUE THREAD

**Issue by Placeholder6** [dyc3/opentogethertube#1123]
### Current Behavior

I soft coded in the subtitles using ffmeg, and are in the mov_text encoding, but either the player doesnt recognise the stream or the button isnt working at all 
![image](https://github.com/dyc3/opentogethertube/assets/86405576/6d6fdd0d-b44f-4eda-b49d-24f1da437266)

### Expected Behavior

player should recognise the subtitle stream, and button should work enabling or disabling subs

### Steps To Reproduce

1. create a room
2. add in a custom video url with embedded subtitles
3. try playing it with subtitles on
4. doesnt work

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This feature relies mostly on how the web browser parses the video.

Would you be able to provide a sample video? It would help a lot with debugging.

**Comment by dyc3** [comment]
Turns out this is a problem with how web browsers work. https://stackoverflow.com/questions/67726220/can-browsers-natively-play-packaged-subtitles-included-in-the-video-file Browsers just don't respect embedded text tracks in mp4 videos.

Closing in favor of #705
