### ISSUE TITLE
harness: consume output of balancer when running tests

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1188]
When running harness tests against the balancer, the balancer outputs a ton of logs. It would be nice if the harness could consume these logs and re emit them so that they don't show up in the output unless `--nocapture` is used. Note that `--nocapture` already exists and so implementing that part is not necessary, eg. `cargo test -- --nocapture`

**Comment by Victor-M-Giraldo** [comment]
I would like to work on this.

**Comment by dyc3** [comment]
We are already using the tracing crate for logging.

You need to grab the standard out and standard error of the child process, and immediately log it back out as the parent process.
