### ISSUE TITLE
balancer: abstract balancing logic into a trait

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1195]
### Is your feature request related to a problem? Please describe.

Currently, the primary logic that actually does load balancing is 2 functions on `BalancerContext`: 
- `select_monolith` - for selecting a monolith to load a new room on
- `random_monolith` - for routing requests that could go to any monolith

If we wanted to try new balancing algorithms, we would have to gut the current one and replace it, making it harder to switch back if it doesn't work (revert the commit, recompile, redeploy). If we had something hot swappable, it should be as easy to switch as a config change and restart. This would also allow for A/B testing of load balancing methods.

### Describe the solution you'd like

- Create a trait that can be used to switch between load balancing algorithms,
- It should attempt to deduplicate the code that prioritizes monoliths in the same region. As such, it shouldn't require implementers of the trait to also implement that logic.
- Ideally, eliminate the need for both `select_monolith` and `random_monolith`.

**Comment by Victor-M-Giraldo** [comment]
I would like to work on this.

**Comment by Victor-M-Giraldo** [comment]
Based on what we spoke about last time the solution to this issue looks something like:

- Define a trait
- Trait should have one method to allocate a room to a monolith.
- Trait should have a method to select a monolith for short lived requests.

Don't `select_monolith` and `random_monolith` already do this (I think)?  

Currently I was thinking of doing something like this.

```
pub trait algorithm_switcher {

fn allocate_room(&self) {
// Code here
}
}
```

and then implementing that trait on BalancerContext
```
impl Algorithm_Switcher for BalancerContext {
}
```

However, this makes the compiler spit out a ton of errors regarding certain functions/traits not being defined in `algorithm_switcher` which makes sense based on my understanding of traits in rust. 

Am I missing something here/going about this the wrong way?

**Comment by dyc3** [comment]
> Don't `select_monolith` and `random_monolith` already do this (I think)?

Yes, but the whole point is not to simply move `select/random_monolith` out of the `impl BalancerContext` block. It's to refactor it so that the balancing logic isn't so tightly coupled to the `BalancerContext`. 

You shouldn't be implementing this trait for `BalancerContext`. Create new types (structs) that can implement this trait, and then `BalancerContext` should have a reference to a type that implements this trait to call functions on it.

It'll probably look something like this
```rust
struct BalancerContext {
    ....
    Box<YourTrait> foo;
}
```

and then in your code that calls on the object with the trait:

```rust
... = self.foo.select_monolith(&candidates);
... = self.foo.random_monolith(&candidates);
```

as a nitpick: `AlgorithmSwitcher` is a terrible name. It describes the purpose (as in why it exists), not the function of the trait (as in what it actually does). An important distinction.

**Comment by Victor-M-Giraldo** [comment]
Okay, that clears up quite a lot of things. I'm going to try and get a draft PR done by today with at least some of that.

Also, yes I agree that `AlgorithmSwitcher` is a horrible name. It was moreso a placeholder because I couldn't think of a name at the time that wouldn't be extremely long. I'll change that.

As a more open ended question, how do you begin to become more comfortable with new repos? Most of the code for OTT is written in a pretty idiomatic way, so when you are looking at it's easy to understand what its purpose is even if you don't understand the implementation. The one problem I've had is making a mental map of things to see how portions of code are related. The documentation and diagrams help with this, but otherwise does it just come from experience?

**Comment by dyc3** [comment]
> but otherwise does it just come from experience?

Pretty much, yeah.
