### ISSUE TITLE
Use `Arc` for room broadcast channels

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1199]
Broadcasting to all clients in a room requires each receiver to `clone()` a new copy of the message, causing unnecessary memory allocations. Wrapping the messages in an `Arc` should allow us to minimize the amount of memory being cloned.

**Comment by Victor-M-Giraldo** [comment]
I would like to work on this.

**Comment by dyc3** [comment]
Closing this because it's not feasible right now, as discussed in #1216
