### ISSUE TITLE
separate toggles for auto-skip categories

### ISSUE THREAD

**Issue by ceofil** [dyc3/opentogethertube#1209]
### Is your feature request related to a problem? Please describe.

I want to auto-skip sponsors but not intros. 
The `Auto-skip sponsored segments, intros, self-promos, etc. using SponsorBlock data.` checkbox does not allow for this behavior.

### Describe the solution you'd like

I would like one checkbox for each type of sponsor block data and one parent checkbox to disable/enable all of them at once for people who like the current behavior.

From the `videoSlider` colors it looks like the type of each auto-skip segment is already known.

If there is no work on this already I would like to implement this myself.

**Comment by dyc3** [comment]
You're correct, the video segments are already known internally, I just haven't gotten around to adding UI for it yet. I'm happy you're interested in contributing, I'll go ahead and assign you the issue.
