### ISSUE TITLE
Add Monolith Discoverer that works for any dns server

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1239]
### Is your feature request related to a problem? Please describe.

Setting up lots of monoliths and balancers locally for testing takes a lot of manual work. docker-compose has a feature where you can scale services:

```bash
docker-compose -f docker/with-balancer.docker-compose.yml up --scale opentogethertube=100 -d
```

### Describe the solution you'd like

Docker provides a dns server to allow apps to do service discovery, similar to Fly. See https://stackoverflow.com/questions/37683508/how-does-service-discovery-work-with-modern-docker-docker-compose

Copy `FlyMonolithDiscoverer` and adapt it to work with docker's dns server.

### Additional context

- Note that the docker containers don't have ipv6 addresses, so you'll have to query the dns server for ipv4 addresses instead.
- You'll also probably need to modify `deploy/ott-balancer-docker.toml` depending on what you name the config options

**Comment by moreno-michael** [comment]
Working on this
