### ISSUE TITLE
make monolith ids constant from the perspective of the balancers

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1251]
Currently, monoliths are assigned a unique `MonolithId` by balancers. However, this makes it extremely difficult to correlate which monolith is which just by querying the balancers. 

- Change the monolith so that it generates it's own id, and conveys it to the balancer in the init message.
- Change the balancer to use this id instead of generating it.
- Add unit tests to the monolith to assert for this new behavior.
    - useful related docs: https://jestjs.io/docs/mock-functions
    - see tests in `clientmanager.spec.ts`

Also update the spec doc to reflect these changes.

**Comment by Victor-M-Giraldo** [comment]
I'd like to work on this.
