### ISSUE TITLE
vis: update `GlobalView` to use `SystemState` type to generate force graph input

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1286]
- Change the dummy data used for the panel to be formatted like is specified in the doc
- Update the code to be able to parse this new data format

**Comment by moreno-michael** [comment]
working on this

**Comment by dyc3** [comment]
This is blocked until #1262 and #1281 are complete

**Comment by dyc3** [comment]
In #1304 I added the `SystemState` type that resembles the data format specified in the doc
