### ISSUE TITLE
make the load balancing algorithm configurable

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1294]
### Is your feature request related to a problem? Please describe.

We want to be able to swap out load balancing algorithms without recompiling.

### Describe the solution you'd like

add an enum of some kind to `BalancerConfig` to make the `MonolithSelection` that is used by the `BalancerContext` configurable.

**Comment by moreno-michael** [comment]
working on this

**Comment by Victor-M-Giraldo** [comment]
I would like to work on this
