### ISSUE TITLE
make monolith discovery polling interval configurable

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1295]
### Is your feature request related to a problem? Please describe.

Currently, this is hard coded at 10 seconds

### Describe the solution you'd like

Add a configuration option somewhere in `BalancerConfig` or any of its inner fields to be able to configure the interval at which Monolith Discovery is polled. This option would be ignored if the discovery method is continuous instead of polling.

**Comment by moreno-michael** [comment]
working on this
