### ISSUE TITLE
balancer: add a command line argument to simply validate the config and exit

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1296]
### Is your feature request related to a problem? Please describe.

I want to be able to validate configs before they reach production and start causing the service to crash.

### Describe the solution you'd like

Add a `--validate` cli arg to the balancer that will load the config specified and if it succeeds without errors, exit immediately with code 0. Otherwise, exit with a non-zero exit code.

**Comment by Victor-M-Giraldo** [comment]
I'd like to work on this.

**Comment by Victor-M-Giraldo** [comment]
Relevant file for this one `config.rs` and the `Cli` struct?

**Comment by dyc3** [comment]
Yes
