### ISSUE TITLE
monolith: add a command line argument to simply validate the config and exit

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1297]
### Is your feature request related to a problem? Please describe.

I want to be able to validate configs before they reach production and start causing the service to crash.

### Describe the solution you'd like

Add a `--validate` cli arg to the monolith that will load the config specified and if it succeeds without errors, exit immediately with code 0. Otherwise, exit with a non-zero exit code.

**Comment by Victor-M-Giraldo** [comment]
I'd like to work on this.

**Comment by Victor-M-Giraldo** [comment]
I'm looking to get started on this. Is the relevant file  `server/config/config.mjs`?

**Comment by dyc3** [comment]
No, you'll need to look at `ott-config.ts` and `app.ts`
