### ISSUE TITLE
Add config in dns discoverer to overwrite dns_server

### ISSUE THREAD

**Issue by moreno-michael** [dyc3/opentogethertube#1337]
### Is your feature request related to a problem? Please describe.

The current solution for #1239 in /crates/ott-common/src/discovery/dns.rs does not account for the case where `self.config.dns_server` is `Some`.

### Describe the solution you'd like

Add the ability for the code to handle the case where `self.config.dns_server` is `Some` to allow overriding the DNS server. When `dns_server` is provided, we should query the dns server provided instead of using the system default.

```mermaid
flowchart TD
    check[Check dns_server]
    check -->|Some| some[use provided DNS server]
    check -->|None| none[use system default]
```

**Comment by cjrkoa** [comment]
I want to pick up this issue
