### ISSUE TITLE
Make balancer IDs constant from the perspective of monoliths

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1338]
### Is your feature request related to a problem? Please describe.

Currently, Balancer IDs are generated by the Monolith. When looking at log output of multiple monoliths, it can get confusing to tell which Balancer is being logged about because the ID for the same Balancer will be different for each Monolith.

### Describe the solution you'd like

Balancers should generate their own ID, and convey it to the monoliths on connect.

### Additional context

This is pretty much like #1251, except the other way around.

**Comment by Victor-M-Giraldo** [comment]
I'd like to work on this.
