### ISSUE TITLE
make `ott-vis-datasource` communicate with `ott-collector`

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1358]
`ott-collector` uses [rocket](https://rocket.rs/) to set up an http server and serve HTTP requests.

This is can be considered done when:
- [ ] `ott-collector` serves system state from the `/state` endpoint (can be hardcoded)
- [ ] `ott-vis-datasource` fetches data from `ott-collector` upon being queried by grafana for data, instead of using hard coded data source

Please write tests.

**Comment by cjrkoa** [comment]
I want this issue
