### ISSUE TITLE
Permissions in permanent room not saving

### ISSUE THREAD

**Issue by Inlifeuser** [dyc3/opentogethertube#1410]
### Expected Behavior

After refresh the page, permissions should not be default, and changes should be noticeable when entering, for example, as an unregistered user.

### Steps To Reproduce

1. Create a permanent room
2. In room settings change permissions
3. Uncheck all or some permissions for unregistered and registered users
4. Click "Save"
5. Refresh room page
6. Check room settings

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Confirmed, I can reproduce this. Whoops. Not sure why this got past our tests.

**Comment by dyc3** [comment]
This appears to be purely a UI bug. For some reason, `PermissionsEditor` is not propagating changes back to the `RoomSettings` component.
