### ISSUE TITLE
ott-vis-panel does not handle large numbers of rooms very well.

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1423]
### Is your feature request related to a problem? Please describe.

In production, there are usually anywhere from 20 to 50 rooms at one time. The panel does not handle this very well.

### Describe the solution you'd like

The visualizations should be adjusted to better handle large numbers of rooms.

**Comment by Victor-M-Giraldo** [comment]
I'd like to work on this

**Comment by dyc3** [comment]
Discussed offline, decided to use TreeDisplay instead for visualization
