### ISSUE TITLE
Weird video size on Safari 14

### ISSUE THREAD

**Issue by damnkrat** [dyc3/opentogethertube#1471]
### Current Behavior

The video zooming in with no reason. No mater it plays or not

### Expected Behavior

Normal video size

### Steps To Reproduce

1. Join room with video
2.  Video keeps zooming in

https://github.com/dyc3/opentogethertube/assets/32395839/b6c1f4f9-2ee7-4807-bc22-ab7f7feb5be6

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Safari 14.1.1
MacOS 11.4

**Comment by dyc3** [comment]
Is this a youtube video?

**Comment by damnkrat** [comment]
1. It is YouTube video
2. I tried on multiple YouTube videos. What do you mean video types?
3. No, it is fine on Firefox

**Comment by dyc3** [comment]
Like direct mp4s or vimeo videos. Does this one so the same thing? https://vjs.zencdn.net/v/oceans.mp4

**Comment by damnkrat** [comment]
No. They are fine

**Comment by dyc3** [comment]
I currently don't have a mac on hand to test with, but I tried to repro using the webkit build for linux, and I can't reproduce it. I'll have to hit up some of my friends with macs.

**Comment by dyc3** [comment]
It appears safari is on v17 by now. I'd recommend upgrading if you can.

I've deployed a speculative fix at https://staging.opentogethertube.com. See if it works, and if it doesn't, send me a screenshot of the javascript console.

**Comment by damnkrat** [comment]
YeS. It does fix the size. Thanks a lot
