### ISSUE TITLE
Start Timer

### ISSUE THREAD

**Issue by stevespaw** [dyc3/opentogethertube#1479]
### Is your feature request related to a problem? Please describe.

This would be amazing if the "host" could add a Start Timer to the Room. Great social media tool to Prebuild a room that goes "live" at a preset time. Things like a Premiere Showing.

### Describe the solution you'd like

Add a Timer to the room to start the Queue.

**Comment by dyc3** [comment]
This would add more logic and UI complexity than I'm comfortable with. You would probably be better served by just embedding it into the source stream, like how youtube does it with youtube premieres.
