### ISSUE TITLE
"add" not obvious 

### ISSUE THREAD

**Issue by stevespaw** [dyc3/opentogethertube#1494]
### Current Behavior

After showing this to colleagues, the main feedback was that they did not see the line where they were to "add" videos. I had to tell each of them where it was. 

### Expected Behavior

If this Line, with maybe a sample was more highlighted - maybe Yellow or Red text? Something to draw attention to the input line. This would be a big help.

### Steps To Reproduce

Click the  "Add" button
Unless you select one of the samples, it is not obvious on what to do next.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Could you elaborate a little more on where they got stuck? I'm a little confused

**Comment by stevespaw** [comment]
On the first one - it is not too bad. But the add text could be much pronounced/highlighted.
![image](https://github.com/dyc3/opentogethertube/assets/11045430/79dbc7e4-bacc-4d53-92df-e877065cb37f)
But adding another if there is one in the list - really confusing, clicking "add" seems to do nothing to the user. 
![image](https://github.com/dyc3/opentogethertube/assets/11045430/035b9df9-8f02-4382-8cb0-1ffa2135afbf)
When it is really wanting you to replace the text in that line..  Make sense?
