### ISSUE TITLE
"Internal server error" in freshly deployed docker image

### ISSUE THREAD

**Issue by bigshit11elf** [dyc3/opentogethertube#1580]
### Current Behavior

I follow the deployment advice. Docker container starts up, container (opentogethertube) is unhealhty, browser is showing "internal server error". (The other containers needed show status "healthy".)

### Expected Behavior

Docker container starts up, container is healhty, website is showing.

### Steps To Reproduce

Follow the deployment advice, open the URL in web browser.

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

**Comment by bigshit11elf** [comment]
Solved it myself - sorry: Did not create api key and session secret. Did that now - error gone.

**Comment by spy-way** [comment]
Hey bro I have same problem can you help me
