### ISSUE TITLE
Need logo and other misc assets

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#16]
Need logo for branding, to be used in these locations:

- favicon
- navigation bar

Should be in SVG format

Assets needed:

- [x] Logo design
- [x] Logo in minimized SVG
- [x] Placeholder image for videos that don't have thumbnail

**Comment by SWSoftware1044** [comment]
Logo design: ~75%
Logo SVG: ~75%
Thumbnail: ~10%

**Comment by dyc3** [comment]
Colors:
orange - #ffb300
blue - #42A5F5
purple - #7d4aef

**Comment by dyc3** [comment]
I did some research, and it looks like svg favicons are a thing, but they aren't well supported. So the favicon has got to be .ico.
