### ISSUE TITLE
vis: add `useColorProvider` hook to manage what colors are being assigned to which nodes

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1608]
### Is your feature request related to a problem? Please describe.

We need to globally manage color assignments in visualizations so that we can render a legend (#1427)

### Describe the solution you'd like

add a `useColorProvider` hook that provides a `color` function to assign colors to things (for use in views), and a Map that contains all the colors that have been assigned and to what (for use in the legend)

**Comment by Victor-M-Giraldo** [comment]
I would like to work on this

**Comment by Victor-M-Giraldo** [comment]
Also giving an update here. Definitely a bit stumped. Wrapping my head around the idea of hooks is weird. Reading through the react docs though and I'll hopefully have made some progress for Tuesday.

**Comment by dyc3** [comment]
You just need to implement the functions in the `ColorProvider` class. The hook is already set up.
