### ISSUE TITLE
Dailymotion videos not working

### ISSUE THREAD

**Issue by Kennsworth** [dyc3/opentogethertube#1627]
### Current Behavior

Black Screen when using daily motion video 
https://dailymotion.com/video/x31i1so 

### Expected Behavior

video plays

### Steps To Reproduce

1. enter room
2. select example daily motion video from list, https://dailymotion.com/video/x31i1so
3. black screen

### Environment

- [x] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

https://dailymotion.com/video/x31i1so 
Google Chrome, Mac

**Comment by dyc3** [comment]
Confirmed, can reproduce. It's been a while since I touched dailymotion, and this doesn't look like a particularly easy fix right now.

**Comment by dyc3** [comment]
Yeah it turns out dailymotion completely changed their player API.

**Comment by dyc3** [comment]
I've taken a closer look at it and made an attempt at fixing it in #1628. I don't think it will be possible to keep dailymotion support around.

The primary problem is that the new dailymotion player has regressed in it's capabilities. It is now completely impossible to set specific settings for the player like disabling the embed's controls, as these settings have been moved such that the owner of the video sets them in their web UI for Dailymotion Studio (which is not available outside of France). This also means that the player could behave very differently on a per video basis, so it would be really hard to get the player to provide a high quality user experience.

**Comment by dyc3** [comment]
After reaching out to the Dailymotion support, they have no plans to address OTT's use case, as part of the missing functionality is a part of "Dailymotion Pro". I don't blame them for deprecating and disabling the old SDK, but it does mean that dailymotion support will need to be removed.
