### ISSUE TITLE
A user without skip permissions can still skip the video, if he has add queue permissions in certain cases

### ISSUE THREAD

**Issue by adrianfurgol** [dyc3/opentogethertube#1657]
### Current Behavior

A user has the following permissions set up:

- manage-queue.add = true
- playback.skip = false

If the user proceeds to search a video and press the play now button, the current video gets skipped and the added video gets played.

### Expected Behavior

If the user proceeds to search a video and press the play now button, it does nothing. Either throw an error or grey out the button.

### Steps To Reproduce

1. Create a room
2. Configure a user with the permissions listed above
3. Search for a video and play it
4. Search for a different video and press the "play now" button
5. The current video gets skipped

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This is actually intended behavior, as the video isn't actually getting skipped -- rather, the currently playing video gets pushed on to the top of the queue (preserving the timestamp it was at). I'll consider this a feature request for a specific "play now" permission.

**Comment by adrianfurgol** [comment]
Did permissions get reset during the update? I just wanted to update my permanent room permissions and had to find out that all permissions are back to default.

**Comment by dyc3** [comment]
They shouldn't have, but it looks like they did.

**Comment by adrianfurgol** [comment]
Okay, thanks for the heads up. And thank you for the quick work 😁

**Comment by dyc3** [comment]
It appears that it's only a UI bug. Permissions didn't actually get reset.

**Comment by adrianfurgol** [comment]
Yes, true. If I reload the tab, the permissions seem to be back to default, but when I join as an unregistered user via incognito tab, the permissions seem to work correctly.
