### ISSUE TITLE
Trusted user has no icon in the user list

### ISSUE THREAD

**Issue by adrianfurgol** [dyc3/opentogethertube#1659]
### Current Behavior

User gets promoted to trusted user. There seems to be a space added for a trusted user icon, and if you hover over the blank space it shows a popup with "trusted user". The icon itself is missing though.

### Expected Behavior

User gets promoted to trusted user. The trusted user icon is added, and if you hover over it, it shows a popup with "trusted user".

### Steps To Reproduce

1. Create Room
2. Promote user to trusted user
3. Enjoy the trusted user blank space

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

![image](https://github.com/dyc3/opentogethertube/assets/38754687/4341cd0f-666a-4bfe-81f4-9163b6e87d41)

**Comment by dyc3** [comment]
Confirmed. Likely introduced in #1499
