### ISSUE TITLE
Service support: Odysee

### ISSUE THREAD

**Issue by LilToaster69** [dyc3/opentogethertube#1691]
### Service Name / Video Format

Odysee

### URL of homepage

https://odysee.com/

### Sample video URLs

Videos: https://odysee.com/@Luke:7/i'll-be-in-mexico,-charlotte,-nc-and:5 - https://odysee.com/@Luke:7/i%27ll-be-in-mexico%2C-charlotte%2C-nc-and:5?r=EGhoAYU1cbYeKdJF8DrMag71R8cyHWze&t=2

Channels: https://odysee.com/@Luke:7 - https://odysee.com/@Luke:7?r=EGhoAYU1cbYeKdJF8DrMag71R8cyHWze

### About the service

- [ ] Service has a public API
- [ ] Service is a paid/subscription service
- [ ] Service requires an API key
- [X] You can access the service via a browser (mobile app not required)
- [ ] Service provides an iframe embed
- [ ] Iframe video playback can be controlled via javascript

**Comment by dyc3** [comment]
Duplicate of #535
