### ISSUE TITLE
Vimeo Seeking failure

### ISSUE THREAD

**Issue by Kennsworth** [dyc3/opentogethertube#1774]
### Current Behavior

when trying to seek specific timestamps in a vimeo video open together tube fails to jump to that timestamp for any room members. The progress bar continues to scroll as if the jump was successful, even ending the video when completed (effectively ending the video early if the user jumps ahead)

### Expected Behavior

when seeking a specific timestamp in a vimeo video all room participants will jump to that timestamp.

### Steps To Reproduce

1. create room 
2. add vimeo video to queue ( https://vimeo.com/94338566 )
3. jump to 40 second mark
4. notice the video doesn't jump

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Room name or URL

https://opentogethertube.com/room/Oysters

### Video URL

https://vimeo.com/94338566 

### Anything else?

Behavior is funny, if the video ends with progress remaining on the progress bar it loops from the beginning. if the progress bar finishes before the video finishes the video ends abruptly.

**Comment by dyc3** [comment]
Confirmed, I can reproduce this. It appears to happen for any Vimeo video.
