### ISSUE TITLE
Adding a video from a playlist loads the whole playlist

### ISSUE THREAD

**Issue by ceofil** [dyc3/opentogethertube#1777]
### Current Behavior

Adding the video from a playlist (https://www.youtube.com/watch?v=<VIDEO_ID>&list=<PLAYLIST_ID>&index=...) loads the whole playlist.

<details><summary>Screenshot</summary>

![image](https://github.com/dyc3/opentogethertube/assets/27892415/37cf5011-7c58-4f70-81ce-0228995dedfb)

<p>

</p>
</details> 

### Expected Behavior

Only the specific video should be added, even if the URL contains playlist information.

### Steps To Reproduce

1. Create a room
2. Add a youtube video from a playlist. (https://www.youtube.com/watch?v=6a-tnmyXjAE&list=PLv-kM7bcufALqOQvMsrVCQCEL1pIWScoQ&index=4)

### Environment

- [X] This happens on the official site, opentogethertube.com
- [x] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This is actually intended behavior, however, it's _supposed_ to put the video in the link at the very top of the list so you don't have to go find it. Can reproduce, def a bug.
