### ISSUE TITLE
More stable and automated deployment

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#180]

**Comment by dyc3** [comment]
Now that we are using redis for state, the only thing preventing me from moving forward with this is the db requirements. Currently looking at heroku, it'll cost $9/month for postgres, since the video cache alone is already over 10K rows

**Comment by antoinebou13** [comment]
Try OVH VPS SSD really cheap 5$/month and you can run multiple databases or docker containers, but I don't know if it's scale with your application.

**Comment by dyc3** [comment]
Moved database over to heroku today.
