### ISSUE TITLE
Playlist disappears from a permanent room

### ISSUE THREAD

**Issue by RedFish87** [dyc3/opentogethertube#1811]
### Current Behavior

After perhaps a couple of hours, my playlist in a permanent room together with some videos selected for the que in the OTU disappear. Is there a way to keep it there, please?

Context: As an English teacher, I’m using OTU as a way to practice listening and understanding with my students. It would be great to have a reliable service that lets me easily navigate through a YT video and be sure that my playlists stay in the permanent room I create

### Expected Behavior

Both playlist and a queue stay in my permanent room.

### Steps To Reproduce

1. Create a permanent room
2. Add playlist, select a few videos for the queue
3. Wait a few hours
4. Both gone

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Room name or URL

https://opentogethertube.com/room/English

### Anything else?

Unrelated to that, there are a few more, minor issues I observe:

- Sometimes the play/pause button bottom left of the video stops working and I need to refresh the page
- It’s not possible to just pause/play by clicking directly onto the window with the video, which is a pity
- Unknown playlists made by other users sometimes appear among "my" rooms, not sure why

**Comment by dyc3** [comment]
Video queues are saved by default, but restoring them requires accepting this prompt below the video

![image](https://github.com/user-attachments/assets/fda68af2-739c-4a3a-8ef9-9f6d5e05a09e)

You can change this behavior in the room settings:

![image](https://github.com/user-attachments/assets/593f9425-42e3-492f-bc1f-7637786d315e)

> It’s not possible to just pause/play by clicking directly onto the window with the video

This is a technical limitation with how iframes work, and with youtube's terms of service. Youtube really doesn't like it when I put UI elements over the embedded video.

> Unknown playlists made by other users sometimes appear among "my" rooms, not sure why

Your room visibility is set to public, which means it shows up in the "Browse" list. You also haven't set permissions to deny random users from adding their own videos or anything.

**Comment by RedFish87** [comment]
Thank you, this has been really helpful.

1) I now see the prompt, because I have turned off the shields of my Brave
browser.
2) Set my room to "Unlisted"
3) Limited permissions for other users
