### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#205]
According to my analytics, we should prioritize

- German
- Dutch
- French
- Italian

Nice to have

- Spanish
- Russian
- Korean
- Chinese
- Japanese

I have do idea how this should be implemented. I'm open to comments and pull requests.

**Comment by XeroxDev** [comment]
Hey @dyc3. I searched a bit and found a nice little [extension](https://kazupon.github.io/vue-i18n/) for vue and translations. I have no idea about vue, but it looks for me exactly like ngx-translate for angular and this is pretty easy without tools and even much easier with BabelEdit. Maybe you could use this?

Kind regards,
XeroxDev

**Comment by dyc3** [comment]
I gonna quickly list out my requirements for localization in order to get it merged in.

- Text must be English by default
- Must not slow down page loads
- Must not affect SEO

Bonus:

- Get English default to appear without an extra network request
