### ISSUE TITLE
No sound on YouTube Videos

### ISSUE THREAD

**Issue by SeineEloquenz** [dyc3/opentogethertube#217]
Since a few days when I try to watch youtube videos with my friends there is no sound anymore.
At the beginning of the video there is a short moment of loud noise and then the video is muted.

It seems this only occurs on YouTube videos as a random dailymotion video I tried had sound.
Reproduced on up-to-date Chrome and Firefox.

**Comment by dyc3** [comment]
For some reason the player is getting muted.

**Comment by dyc3** [comment]
Should be fixed now.
