### ISSUE TITLE
Not playing certain youtube free movies

### ISSUE THREAD

**Issue by antonpictures** [dyc3/opentogethertube#228]
https://www.youtube.com/watch?v=KON9iSZqH7U

![Screen Shot 2020-03-27 at 4 51 16 PM](https://user-images.githubusercontent.com/4306109/77809505-25f7a200-704d-11ea-9815-d7791e0c2005.png)
![Screen Shot 2020-03-27 at 5 04 56 PM](https://user-images.githubusercontent.com/4306109/77809509-28f29280-704d-11ea-86b8-b95ac70e4f25.png)

**Comment by dyc3** [comment]
Closing as duplicate of #225
