### ISSUE TITLE
YouTube livestream error

### ISSUE THREAD

**Issue by antonpictures** [dyc3/opentogethertube#229]
https://www.youtube.com/watch?v=9Auq9mYxFEE video plays one sec then stops.   in this temp room.  the only room I have found on opentogether  https://opentogethertube.com/room/3b3a226c-dd8a-4051-887d-00206de096cc

**Comment by dyc3** [comment]
Livestreams are not yet supported. This is a planned feature

**Comment by antonpictures** [comment]
on https://cytu.be/r/SkyNews seems t be working. is the embed code different?

**Comment by antonpictures** [comment]
are you busy bro?


-------- Original Message --------
Subject: Re: [dyc3/opentogethertube] YouTube livestream error (#229)

**Comment by dyc3** [comment]
Supporting livestreams requires a significant rework on the server side. Since youtube livestreams return a duration of 0 seconds, when the video starts playing, the server sees that the playback position has exceeded the video duration, and tries to play the next video in the queue.

**Comment by dyc3** [comment]
I thought I had an issue open for this already, but apparently I didn't. I'm closing this in favor of a proper feature request, see #231

**Comment by antonpictures** [comment]
Hi Carson,


I want a website like Pluto.tv
Based on cytu.be code or similar and use as sources the youtube live streams and customized playlists.

Can you do that?

Thank you. 
George

**Comment by antonpictures** [comment]
oh, you closed the issue. I hope you read this.   Best, GeorgeAnton.com

**Comment by dyc3** [comment]
Please open a new issue to ask questions that aren't related to this one.
