### ISSUE TITLE
https://opentogethertube.com/rooms

### ISSUE THREAD

**Issue by antonpictures** [dyc3/opentogethertube#235]
how to embed the youtube TV window on the main cytu.be channel list?
so i can change the channels and Watch TV on ONE single PAGE.

![main page - watch tv and change channels](https://user-images.githubusercontent.com/4306109/78078514-323a7280-735f-11ea-9250-6f7ed5f83e7a.png)
![admin panel - edit channels and playlists copy](https://user-images.githubusercontent.com/4306109/78078548-3f576180-735f-11ea-87ec-d85384339995.jpg)

**Comment by dyc3** [comment]
What does this have to do with OpenTogetherTube?
