### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#249]
Currently, all the API endpoints are basically undocumented.

**Comment by dyc3** [comment]
I've started to document all api endpoints using optic.

**Comment by Graxo** [comment]
I keep getting "app error OPENTOGETHERTUBE_API_KEY is invalid." how can i check what i invalid? I use a generated string of 40 chars.

**Comment by dyc3** [comment]
@Graxo Would you mind opening a separate discussion post for that? Please provide as much information as you can.
