### ISSUE TITLE
Request timeout when registering duplicate user

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#259]
## Current Behavior
The register form gets put in to the loading state until the request times out.

### How To Reproduce

1. Register new user
2. Log out
3. Attempt to register the same user using exact same credentials
4. Form put in loading state until request times out

## Expected behavior
Expected the server to send a response saying the email and username is already in use.

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.

#### Additional context
Server logs
```
2020-04-20 10:21:26 usermanager error Failed to create new user in the database: SequelizeUniqueConstraintError: Validation error Validation error
2020-04-20 10:21:26 usermanager error Unable to register user SequelizeUniqueConstraintError: Validation error Validation error
(node:26663) UnhandledPromiseRejectionWarning: TypeError: err.fields.join is not a function
    at usermanager.registerUser.then.catch.err (/home/carson/opentogethertube/usermanager.js:180:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:26663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:26663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by elenirotsides** [comment]
Hi @dyc3 I think I can handle this one, I'd love to give it a go! Would you be able to point me in the right direction? Not sure which files need to be touched. Also, any pointers in regards to accessing the database would also be helpful, since what I've done previously has been quite different from this. Thanks!

**Comment by elenirotsides** [comment]
Actually wait, I just tested this, and I can't seem to reproduce this issue. I just noticed that this was opened quite a while ago, is it possible there have been changes made that inadvertently fixed this?

**Comment by dyc3** [comment]
Yup, I think I accidentally fixed this a while ago
