### ISSUE TITLE
Enter should submit log in form

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#267]
**Is your feature request related to a problem? Please describe.**
Most users expect to have the enter button submit a log in form.

**Describe the solution you'd like**
When enter is pressed while the log in form is focused, it should submit the form and attempt to log in.

**Describe alternatives you've considered**
The log in button is an alternative that already exists.

**Additional context**

**Comment by elenirotsides** [comment]
@dyc3 I'd like to take a stab at this one too, if that's okay! So just to clarify, you'd like the enter key to submit the log in form, correct? And it currently does nothing?

**Comment by dyc3** [comment]
That's correct
