### ISSUE TITLE
Clients leave and join without user interaction at seemingly random intervals, which spams leave/join notifications

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#272]
## Current Behavior
The Join-Notification Snackbar pops up repeatedly in unspecific interval. This means: I join a room. Watch Videos and get in random interval the Join-Notification of me or other users displayed.

### How To Reproduce
Just watch Videos and wait. Maybe it's cause of a short connection loss due SocketIO?

## Expected behavior
Just show the Snackbar, if the user really joined the room.

## Environment
- [x] This happens on the official site: opentogethertube.com
- [X] This happens using a self-hosted version.

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox & Chrome
 - Version: FF 77.0.1 | Chrome 83.0.4103.106

**Comment by dyc3** [comment]
I think I know what is causing this. If messages are not being sent through the socket, then connections are dropped. The websocket spec says that this timeout interval should be 100 seconds.

Are you hosting it using a reverse proxy? Here's the relevant part of my nginx config, in the `location /` directive:
```
proxy_connect_timeout 7d;
proxy_read_timeout 7d;
proxy_send_timeout 7d;
```

**Comment by XeroxDev** [comment]
Yes. I'm using a reverse proxy (nginx). I'll add your 3 lines and test, if this will fix it. :)

**Comment by XeroxDev** [comment]
This seems to be the fix. Maybe you can add this to the readme or wiki, so other people don't have this problem :D But thank you for your quick response! I let you close the ticket, so you can reference this issue to the commit :D

**Comment by dyc3** [comment]
I think it would be better if that configurations was not necessary at all. I think a keepalive message of some sort would do the trick. Leaving this open until we try that out.

**Comment by dyc3** [comment]
After moving to heroku, this bug resurfaced.

**Comment by dyc3** [comment]
According to the heroku docs, the connection timeout is 30 seconds. https://devcenter.heroku.com/articles/request-timeout
All we need to do is increase the frequency of the ping messages to keep the connection alive.
