### ISSUE TITLE
Small problem with Fullscreen Scrollbar

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#273]
## Current Behavior
If you go into fullscreen mode (with F or Fullscreen button from the site) the scrollbar is still visible. It's not a hard bug, but it's not real fullscreen either :D

### How To Reproduce
Just go into fullscreen mode. Little css tweaks and it's fixed :D

## Expected behavior
Scrollbar should be disabled or invisible (if you want to allow the user to scroll like in youtube videos) in fullscreen.

## Environment
- [x] This happens on the official site: opentogethertube.com
- [X] This happens using a self-hosted version.

### Desktop (please complete the following information):
- OS: Windows 10
- Browser: Firefox & Chrome
- Version: FF 77.0.1 | Chrome 83.0.4103.106

**Comment by dyc3** [comment]
What's your screen resolution? I'm assuming it's 1080p right?

**Comment by XeroxDev** [comment]
Yes. It is.

**Comment by elenirotsides** [comment]
Hi! @dyc3 I'd like to take a stab at this!
