### ISSUE TITLE
Problem with claim Room Feature

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#274]
## Current Behavior
If you claimed your room, with your account, after a unspecific amount of time / browser closed / cleared cache, you can / need to claim the room again.

### How To Reproduce
Unknown how to reproduce it to 100% but I noticed it multiple times, after I went to my room again after some time / next day and looked into settings.

## Expected behavior
Should stay claimed.

## Environment
- [x] This happens on the official site: opentogethertube.com
- [X] This happens using a self-hosted version.

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox & Chrome
 - Version: FF 77.0.1 | Chrome 83.0.4103.106

**Comment by dyc3** [comment]
On the backend, rooms do stay claimed. I think it has something to do with how the state is communicated to the client.

**Comment by dyc3** [comment]
Found a method to reproduce:

1. Create a permanent room that is unclaimed.
2. While logged in, try to claim the room.
3. Unload the room by sending a delete request to the room.
4. See that the sync message says that the room is not claimed (`hasOwner` is false).
