### ISSUE TITLE
Consistent code style

### ISSUE THREAD

**Issue by Butt4cak3** [dyc3/opentogethertube#280]
I'm currently trying to become familiar with the code while making a couple of changes that I will soon submit as pull requests. I quickly noticed that there is a lot of inconsistency when it comes to things like indentation and quotes. I can work around these things, but I'd like to know what to do to not make things worse when contributing.

I'm personally a fan of [EditorConfig](https://editorconfig.org/), code formatters (specifically [prettier](https://prettier.io/)) and the "Format On Save" option in VSCode. I don't request you to immediately work towards integrating these into the project. However, they make life a good bit easier for developers and especially for (new) contributors and they let you focus more on writing code rather than making it look nice.

**These are the questions I want to answer with this issue:**

1. What should my code look like if I want to contribute to the project?
    1. Should I use tabs or (2) spaces?
    2. Should I use double or single quotes in .js and .vue files?
2. How do you feel about working towards a more consistently styled code base? Would you consider employing a code formatter in the long run? Where is this issue on your list of priorities, if it's there at all?

**Comment by dyc3** [comment]
I'm well aware that it can feel a bit messy. The bits of code style that I care about are already enforced by eslint. Everything else I don't really care about.

If you want to contribute, just make sure `npm run lint` succeeds. As long as tabs/spaces are consistent in the same file, it doesn't really matter. I don't really care about double or single quotes, but I prefer double.

I haven't found the lack of consistent style to be a blocker to new contributors. Everything that I would nitpick in a PR style wise is caught by eslint.

**Comment by Butt4cak3** [comment]
Alright, thanks. That sums it up quite well. I'll keep that in mind and continue working on what I've done so far. Knowing myself, I will probably come back to this later. But for now, I'll focus on getting a couple of things done.
