### ISSUE TITLE
Videos synced incorrectly when server's time and client's time is different

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#290]
## Current Behavior
Hello. We have a synchronization problem. When friends and I watch YouTube videos together, we are not completely synchronized (there are about 20-30 seconds difference). As soon as we try to get to the same time by pausing or rewinding, strange events happen. As soon as you pause the video jumps forward 10 seconds and as soon as you play it again it jumps back 10 seconds. A similar behavior can also be seen with fast forward / rewind.

### How To Reproduce
- Insert Video.
- Let it play.
- Pause or fast forward / rewind

## Expected behavior
All should be at sync (with maximal 2-3 seconds delay) and if you pause or rewind, it should stay / jump at / to the correct time.

### Screenshots
![b69d](https://user-images.githubusercontent.com/10864620/90332597-70f36100-dfbe-11ea-8dad-f14ff547c56e.png)

## Environment

- [ ] This happens on the official site: opentogethertube.com | Couldn't be tested because I can't connect to rooms (tested with Chrome and FireFox latest versions)
- [X] This happens using a self-hosted version.

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome, FireFox
 - Version Newest Versions

**Comment by dyc3** [comment]
What's the latest commit that `git log` gives you?

**Comment by XeroxDev** [comment]
Before I created this Issue, I fetched, pulled and rebuild the code and tested again, so I'm on the latest commit (commit e0679115d21db8eb439082c238869bdcf34c9edc (HEAD -> master, origin/master, origin/HEAD))

**Comment by dyc3** [comment]
Is your computer's time correct? The video synchronization relies heavily on having the correct date/time

**Comment by XeroxDev** [comment]
I re-synchronized my computer with the time server and that fixed the error (why it was always out of sync when it should be doing it every day). However, I don't find this a good method to synchronize people with each other, because you can't always assume that everyone is synchronized with the time, especially not if they are not that technology-savvy. But what interests me now ... What happens when users have different time zones? Has it been thought of or could it lead to problems?

However, I would really advise against this method and let this be done entirely via the server.

But thank you for the help.

**Comment by dyc3** [comment]
We didn't always use the time to sync the video, but the problem with the previous method was that it required messages to be sent to the client every second (at least with the way we had it architected). As for time zones, the timestamps used include time zone, so we let moment.js handle that burden.

We could probably make this a little better though. I can think of a couple of possible solutions:

1. Let the client determine the timestamp at when playback started, so the server doesn't need to send the timestamp.
2. Have the client and server negotiate the client's time span offset from the server's time.

**Comment by XeroxDev** [comment]
Isn't it possible to do that completely without a time? For example, just to transfer the timestamp of the video as soon as the user changes something in the video? Because I wouldn't think of any way to change the time of the video in normal use without JavaScript noticing.

Or would that cause problems?

**Comment by dyc3** [comment]
If a video buffers on one client, but not the others, and we aren't ensuring the client knows what the video's position is supposed to be, then that client's video will lag behind the others.

**Comment by XeroxDev** [comment]
Mh.. That's right.. But what you have to think about more carefully.. What if, as an example, 5 people are connected, everyone has a different time for some reason. How would that be handled?
