### ISSUE TITLE
HOSTNAME value from config is ignored

### ISSUE THREAD

**Issue by mrjohnson22** [dyc3/opentogethertube#293]
## Current Behavior
The value of `HOSTNAME` set in an `env/<mode>.env` config file is ignored. Instead, `HOSTNAME` is always set to the hostname of the running machine. This fails the validator check and causes a failure on startup.

### How To Reproduce
1. Create `env/development.env` or `env/production.env`and set `HOSTNAME` to `localhost:8080`, `127.0.0.1:8080`, or any address/port combination
2. Run `npm run start` or `env NODE_ENV=production npm run start`
3. See an error message of `error HOSTNAME is invalid.`
4. Optionally, add this between lines 48 and 49 of `app.js`:

```
log.info(`${configVar} is ${process.env[configVar]}`);
```
This will print the value of all config variables. The entry for `HOSTNAME` will always say `app info HOSTNAME is <hostname_of_machine>`, instead of `HOSTNAME is <value_from_config>`.

## Expected behavior
Opentogethertube should use the value of `HOSTNAME` from the config file.

## Environment

- [ ] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.

### Desktop (please complete the following information):
 - OS: Fedora 32

#### Additional context
Renaming `HOSTNAME` to something else, like `MYHOSTNAME`, fixes the problem.

**Comment by dyc3** [comment]
`HOSTNAME` has been renamed to `OTT_HOSTNAME`
