### ISSUE TITLE
Direct videos fail with "No compatible source was found for this media"

### ISSUE THREAD

**Issue by mrjohnson22** [dyc3/opentogethertube#295]
## Current Behavior
When playing a video from a direct URL, the video fails to play, displaying an error message of "No compatible source was found for this media".

The browser console (in Firefox, at least) shows `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.`

I have tested this with mp4 and ogv videos.

### How To Reproduce
1. Add or join a room
2. Click "Add" and add either of these videos:
  - https://brionv.com/misc/tram/barf2-newer.mp4
  - https://upload.wikimedia.org/wikipedia/commons/4/42/Cat.ogv
3. Click the + button
4. Play the video (skip queued videos if necessary)

## Expected behavior
The video should play.
Note that the video plays when visiting the video URL itself. That means this is not an issue of codecs not being available to the web browser.

### Screenshots

![ott-error](https://user-images.githubusercontent.com/8988672/91527517-eb33b780-e8d3-11ea-80d1-97f3f89ee0b9.png)

## Environment
- [x] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.

### Desktop:
 - OS: Fedora 32 Workstation Edition 64-bit
 - Browsers:
    - Firefox 80
    - chromium-browser-privacy 84.0.4147.125
    - Gnome Web 3.36.4

### Smartphone:
 - OS: Android Pie
 - Browsers:
    - Firefox Nightly 200826
    - Chrome 84.0.4147.125

**Comment by dyc3** [comment]
Yeah, unfortunately direct videos are kinda buggy, and it heavily relies on videojs to work as expected. We might just need to update videojs. Thanks for the super detailed bug report though! This will be super helpful for fixing this.

**Comment by dyc3** [comment]
I tried updating video.js to the latest version, and this bug still happened. However, I tried just using video.js in this code pen and the provided videos worked: https://codepen.io/heff/pen/EarCt So something weird is going on, and I don't think it's video.js' fault.

**Comment by dyc3** [comment]
We _may_ have goofed a little bit when refactoring the player on the client side.
