### ISSUE TITLE
Room can get unusable cause of Video-Bug

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#301]
## Current Behavior
Sometimes while adding a video the room get unusable. The Video has no timestamp, you can't skip the video, you can't really interact with the video and so on.

### How To Reproduce

Unknown (I think it happens, when you add a video in the exact time the other video ends)
## Expected behavior
Video should still be able to skip, controls and so on.

### Screenshots
This screenshot shows a playing video
![d989](https://user-images.githubusercontent.com/10864620/93688105-a9a5bf00-fac3-11ea-8284-c1ffc869dc7e.png)

## Environment

- [ ] This happens on the official site: opentogethertube.com
- [X] This happens using a self-hosted version.
    - [X] I'm using the docker image.

### Desktop (please complete the following information when applicable):
 - OS: Windows 10
 - Browser firefox and google chrome
 - Version both latest

#### Additional context
This happend already twice and everytime I need to delete everything and reinstall OpenTogetherTube

**Comment by dyc3** [comment]
This needs more information to fix.

In the meantime, when this happens, you can clear the room's state by telling it to unload:
```
curl -X DELETE http://localhost:3000/api/room/ROOMNAME
```
which I think will fix it.

**Comment by XeroxDev** [comment]
Sadly I don't know how to add more information. The logs are normal, the console is normal and I don't know how to reproduce it.. Sorry :c

**Comment by XeroxDev** [comment]
More information: It happend again, I executed the curl command. State was removed, we could add a new video but the very next video has the bug again.

I have a Idea. I can send you my room url. Maybe use any Chat program we both have and try to search the reason together?

**Comment by XeroxDev** [comment]
We found the reason. It is depending on the video (https://www.youtube.com/watch?v=h4aEZp8DBG8) this cause to a "crash". I think it's because of the warning in front of the video.

Here is a screenshot of the video (warning): 
![image](https://user-images.githubusercontent.com/10864620/93717872-cbad4900-fb78-11ea-9c6b-d937fe3a7cd0.jpeg)

**Comment by dyc3** [comment]
I tested that video on the main site, and it works. Maybe the embed checks to see if you are signed in? I didn't get that warning when watching it normally on youtube.com, but I did get it when in an incognito window. I also tried playing that video in an OTT room in incognito mode and it worked fine.

**Comment by dyc3** [comment]
From the Youtube API in the `contentDetails` part, this video is age restricted:
```json
"contentRating": {
     "ytRating": "ytAgeRestricted"
},
```

**Comment by XeroxDev** [comment]
I don't see this message either. A friend of mine said to me, the Video has this message. (But everyone of us is over 18 y/o). But it must have to do with this. It only happens with those videos.

**Comment by dyc3** [comment]
Hey, is this still a problem? I can't seem to reproduce it.

**Comment by XeroxDev** [comment]
Has not turned up in the meantime. If it happens again, I can reopen the issue.
