### ISSUE TITLE
Register modal - inputs are shifting in Chrome

### ISSUE THREAD

**Issue by elenirotsides** [dyc3/opentogethertube#313]
## Current Behavior
When the user navigates to the Register modal, the input fields are disoriented. When you start typing in the password field, it moves to the second line adjacent to the Retype Password field

### How To Reproduce

1. Navigate to OpenTogetherTube in Chrome (bugs occurs in locally hosted version and on the official site - take your pick)
2. Click on 'Log In' in the top right corner of the page
3. Click the 'Register' tab
4. Observe the behavior upon initially viewing the modal, and then again when you begin typing in the password field

## Expected behavior

The input fields should not be shifting around.

### Screenshots

<img width="654" alt="image" src="https://user-images.githubusercontent.com/43190242/97064216-51565700-1572-11eb-96c5-3e59cca94f8c.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/43190242/97064267-af833a00-1572-11eb-8f4b-f77dde773093.png">

## Environment

- [x] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

### Desktop (please complete the following information when applicable):
 - OS: Mac OS
 - Browser Chrome

**Comment by dyc3** [comment]
I am not able to reproduce this.
