### ISSUE TITLE
Refactoring: New Slider Component

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#319]
The current slider from the `vue-slider` package is a relic from when I was first prototyping the website. It's worked great so far, but it has started to get in the way of UX. We need to create a new slider that meets the following requirements:

- Must not use `this.$store` at all
- Must be able to display value when the mouse is hovered over different parts of the bar in a tooltip
    - Like a youtube video's slider
    - Should not be default behavior, opt in with a boolean prop
- Must be able to customize string format of slider value tooltip with a function.
- Must emit `dragStart`, `dragChange`, `dragEnd` events when the user drags the slider
- Must be able to highlight different sections of the slider with different colors, independent of the slider value.
   - For example, the 0-5 range could be marked blue, and the 13-20 range could be marked green.

**Comment by elenirotsides** [comment]
@dyc3 Can you assign me? I'll start taking a look at this!

**Comment by elenirotsides** [comment]
A few questions!

> Should not be default behavior, opt in with a boolean prop
Can you please elaborate on what you mean here? 

> Must be able to customize format of slider value tooltip with a function.
Can you explain this a bit further, too? I know what a tooltip is, but what do you mean by 'customize format of slider'?

> Must be able to highlight different sections of the slider with different colors, independent of the slider value
Do you just mean that the color of the slider needs to be rainbow-ish (independent of the value, of course)? Not a solid color, but while still sticking with the color scheme of the site, fade into different colors as the video progresses? If I interpreted that correctly, wouldn't that be a bit distracting? I guess what I'm asking is, is there a specific use-case I need to keep in mind while designing this, or is this just to introduce a new aesthetic to OTT?

The past few days I've been trying to research different ways to do this, but it doesn't seem like there's much information out there about how to approach this. I'm assuming you want me to completely axe the `vue-slider-component` and just build a fresh one, right? Or, is this package a configurable one I can edit to suit the current needs of OTT? (Speaking of which, I think there's a new version of this but its in the beta state currently: https://www.npmjs.com/package/vue-slider-component ?)

_Also, this is my first major project outside of what I've done for school, so this may take me a while to figure out. I'm super stoked to take a stab at this though, just expect lots of questions from me!_

**Comment by dyc3** [comment]
> Should not be default behavior, opt in with a boolean prop

The described behavior should not be the default behavior of the component. Instead it should be opt-in by setting a boolean property on the component to true.

> Must be able to customize format of slider value tooltip with a function.

Customize the _string_ format of the value shown on the tooltip. For example, instead of showing a number it could show a timestamp.

> Must be able to highlight different sections of the slider with different colors, independent of the slider value

We must be able to provide any number of value ranges to the slider, and be able to use different colors to mark those ranges on the slider. These marks should always be shown, and should remain a constant color, regardless of what the slider value is.

In this example, youtube's slider is shown with different time ranges marked with different colors. We should be able to do that with our slider.
![2020-11-18-175806_1882x62_scrot](https://user-images.githubusercontent.com/1808807/99598535-ad709780-29c7-11eb-85b6-eaa7cc4e7d8a.png)

>  I'm assuming you want me to completely axe the vue-slider-component and just build a fresh one.

Yup. 


As for getting started, I would first figure out how to make an element dragable with constraints. Then you can figure out how to put it in a vue component.

**Comment by dyc3** [comment]
This might not be necessary anymore. vue-slider-component has the `process` prop, which allows us to display extra intervals on the slider. Closing for now.
