### ISSUE TITLE
Service adapter documentation

### ISSUE THREAD

**Issue by Butt4cak3** [dyc3/opentogethertube#324]
I wrote up some documentation for the ServiceAdapter interface so you and others can start implementing their own services. You can find it in my fork's wiki. Feel free to copy it as-is or make changes as desired.

https://github.com/Butt4cak3/opentogethertube/wiki/Dev:-Adding-video-services

**Comment by Butt4cak3** [comment]
@dyc3 Is something wrong with this? It's been a week and I thought I might ask.

**Comment by dyc3** [comment]
Ah, I completely forgot about this. I'll add it to the wiki now

**Comment by antoinebou13** [comment]
Thank i will use this for the spotify service adapter

**Comment by Butt4cak3** [comment]
@antoinebou13 Also feel free to ask questions or make suggestions for the interface. If you open a pull request for the adapter I'll gladly help you get it done.

**Comment by antoinebou13** [comment]
@Butt4cak3 The documentation is pretty clear. I currently work Spotify service adapter and that was pretty easy to set up using your template. Now, I just need to learn how to use the Spotify Web API and copy-paste the API inside the service adapter. I set your up as a reviewer on my PR when I have something functional.
