### ISSUE TITLE
Video searches/playlists/channels don't return video metadata in results

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#325]
## Current Behavior
Sometimes, when you search using the add preview box, the videos don't show up.
In the search results, `title`, `description`, `length`, `thumbnail` are all null, which is expected. However, `getManyVideoInfo` with these videos returns `undefined`.

### How To Reproduce

1. Open a new room
2. Put a search query, youtube playlist, or youtube channel in the add preview box
3. See that there are no results, and no error is displayed to the user.

## Expected behavior
Add preview should return results for valid requests

## Environment

- [x] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

#### Additional context
I've rolled back the deployment on heroku until this is fixed. Ironic that all that manual testing didn't catch this.

@Butt4cak3 

Known bad inputs:
- `https://www.youtube.com/c/AlexMoukalaMusic`
- `https://www.youtube.com/channel/UCL7DDQWP6x7wy0O6L5ZIgxg`
- `spacex launch`
- `https://www.youtube.com/playlist?list=PLABqEYq6H3vpCmsmyUnHnfMOeAnjBdSNm`

**Comment by Butt4cak3** [comment]
What's "sometimes" in this context? Randomly or for specific inputs?

**Comment by dyc3** [comment]
I've updated the issue with known bad inputs. I was getting successful queries earlier but it seems to happen 100% of the time now.

**Comment by Butt4cak3** [comment]
Alright. I found two issues.

1. Some of the nullish checks in `InfoExtractor` are broken. Therefore `missingInfo`/`onlyProperties` was empty. See https://github.com/dyc3/opentogethertube/pull/284#discussion_r523551041
2. I fixed issue 1 locally but it still didn't work. For some reason, I had duplicate cache entries for some videos. Once I cleared my cache database, everything worked just fine. I couldn't reproduce the double caching, but I'm assuming that it has to do with the issue outlined here https://github.com/dyc3/opentogethertube/pull/284#issuecomment-727256574

**Comment by Butt4cak3** [comment]
I can create a PR if you want me too. I'd revert the code to use `== null` where it's required and set the "eqeqeq" rule in ESLint to "smart", which disallows double-equals in comparisons, except when comparing with `null`.

**Comment by dyc3** [comment]
I see. I think the better solution would be to just check for fasly values, since each of those fields are supposed to have non falsy values anyway. It would be great if you could send a PR

The eslint rules aren't being completely enforced anyway for some reason. See #323
