### ISSUE TITLE
Jest unable to mock functions in the new info extractor

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#328]
While working on getting test coverage up, I found that jest was not able to mock any of the functions in `infoextractor.js`.

The following example test case succeeds:

```javascript
it("should be able to mock", async () => {
	let getManyVideoInfoSpy = jest.spyOn(InfoExtractor, 'getManyVideoInfo').mockResolvedValue([new Video()]);
	await InfoExtractor.getManyVideoInfo();
	expect(getManyVideoInfoSpy).toBeCalledTimes(1);
	getManyVideoInfoSpy.mockRestore();
});
```

However, the following fails when it should succeed:

```javascript
it("should use mocks instead of real functions", async () => {
	let getCachedSearchResultsSpy = jest.spyOn(InfoExtractor, 'getCachedSearchResults').mockResolvedValue([new Video()]);
	try {
		await InfoExtractor.searchVideos("test", "asdf");
	}
	catch {
		// ignore
	}
	expect(getCachedSearchResultsSpy).toBeCalledTimes(1);
	getCachedSearchResultsSpy.mockRestore();
});
```

**Comment by dyc3** [comment]
The issue was that the info extractor module was referencing the functions internally, not using the versions of the functions that were exported. The exported functions were mocked, but the way it was set up the mocks were bypassed.

Will be fixed in my next test coverage PR

**Comment by Butt4cak3** [comment]
What the hell... I'm looking forward to seeing that PR.

**Comment by dyc3** [comment]
I'm definitely doing a bad job of explaining it, the code will explain it a lot better.

**Comment by Butt4cak3** [comment]
Oooh... I see. I wonder if there's another way to handle this. Having to write the internal code in a certain way so that tests can mock certain functions seems kinda weird. But maybe that's just part of writing testable code. I don't know.
