### ISSUE TITLE
Occasional skipping when playing long videos

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#33]
This probably has something to do with `setInterval` not being super accurate. Maybe instead of adding 1 second to playback progress every tick, check the actual time delta since the last tick?

**Comment by adapap** [comment]
https://stackoverflow.com/questions/42381912/how-to-synchronize-data-between-multiple-clients-on-node-js-server

**Comment by dyc3** [comment]
Found a package that provides a more accurate timer: https://github.com/Krb686/nanotimer
