### ISSUE TITLE
Youtube links from user's liked videos don't work

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#330]
## Current Behavior
Links like:
```
https://www.youtube.com/watch?v=MVUWcX1aZnk&list=LL&index=133&ab_channel=BrianJordanAlvarez
```
don't work in the add preview

### How To Reproduce

1. Put the link in the add preview box.

## Expected behavior
Add preview should return 1 video.

## Environment

- [x] This happens on the official site: opentogethertube.com
- [x] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by Butt4cak3** [comment]
I don't think this is possible without linking accounts and tapping into the user's private playlists. So I guess we have to explicitly add "LL" as an edge case. I'm gonna open a PR real quick.

**Comment by dyc3** [comment]
Well, if we fail to get the playlist, it should just return the video as if we inputed
```
https://www.youtube.com/watch?v=MVUWcX1aZnk
```

**Comment by Butt4cak3** [comment]
Actually, while I'm at it, I'll try to detect whether a playlist is private or not. That'll catch more error cases.
