### ISSUE TITLE
Service support:  aniwatch.me (Hard)

### ISSUE THREAD

**Issue by antoinebou13** [dyc3/opentogethertube#333]
Name of service: aniwatch.me
URL of homepage: https://aniwatch.me

Sample video URLs
1. https://aniwatch.me/anime/2549/7
2. https://aniwatch.me/anime/54/1

- [ ] Service has a public API
    - [ ] Service requires an API key
- [ ] Service provides it's own iframe embed
    - [ ] Video playback can be controlled via javascript

React with 👍 if you are interested in this.

**Comment by dyc3** [comment]
I reached out to aniwatch.me on discord, and they do not want us to add support on OTT.
