### ISSUE TITLE
Seek video via text input

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#336]
**Is your feature request related to a problem? Please describe.**
Seeking to a specific timestamp is a pain sometimes, especially in long videos.

**Describe the solution you'd like**
The user should be able to click the current timestamp to activate a text box to input a new timestamp. <kbd>Enter</kbd> should confirm the operation. <kbd>Esc</kbd> should cancel the operation. Unfocusing the text box should cancel the operation.

**Comment by Butt4cak3** [comment]
How about adding clickable timestamps in chat along with this?

**Comment by dyc3** [comment]
I like that! And it would be pretty easy to implement in the `ProcessedText` component
