### ISSUE TITLE
how to run on https?

### ISSUE THREAD

**Issue by vampiebar** [dyc3/opentogethertube#343]
Hello,

How can I run in https ?

Do I need to add something like?

var fs = require('fs');

var tls = {
  key: fs.readFileSync('/home/vampie/ssl.key'),
  cert: fs.readFileSync('/home/vampie/ssl.cert')
};

//server.connection({address: '0.0.0.0', port: 443, tls: tls });
//server.connection({address: '0.0.0.0', port: 80 });

// Configure Server
server.connection({ port: ~~(process.env.PORT), tls: tls });

**Comment by dyc3** [comment]
No, you're intended to use a reverse proxy to handle https, like nginx.
See: https://github.com/dyc3/opentogethertube/wiki/Deploy:-Self-Hosted---Reverse-Proxy

**Comment by dyc3** [comment]
Closing as resolved. If you still need help with this, feel free to reply here.
