### ISSUE TITLE
What is the license for OTT?

### ISSUE THREAD

**Issue by maddie-wang** [dyc3/opentogethertube#378]
Hey! I was wondering what the license is for OTT!

Not sure if I'm legally allowed to modify the code, but I was really hoping to play around with OTT! :D

Do you guys mind adding a license? I think it should be pretty quick!

Thanks so much!

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by dyc3** [comment]
Fixed

**Comment by maddie-wang** [comment]
Thanks so much !!
