### ISSUE TITLE
Emby Support

### ISSUE THREAD

**Issue by Kippenhof** [dyc3/opentogethertube#384]
**Is your feature request related to a problem? Please describe.**
I cant use Emby in Opentogethertube

**Describe the solution you'd like**
An Offitial Emby-Intigration would be nice

**Describe alternatives you've considered**
Sharing my Screen over Discord, but the Quality is poor

**Additional context**
An Official Emby-Support would be great! I am using Emby quite some Time Now, and it would be nice if you could use it easily on Opentogethertube.

**Comment by dyc3** [comment]
Could you use the "Service support request" template instead?

**Comment by Kippenhof** [comment]
I checked the Documentationsy and without an Plugin in Emby, I don't think an Integration is possible
