### ISSUE TITLE
Running the server under a different URI

### ISSUE THREAD

**Issue by RandomWolf** [dyc3/opentogethertube#388]
Hi!

I would like to run this server under a different URI, for example https://domain.com/sync, instead of just domain.com

But when I cofnigure nginx as the reverse proxy with the "location ~/sync" modifier, 
```
server {

server_name domain.com;

location ~ /sync  {
proxy_pass http://127.0.0.1:3000;
[...]
```

and open domain.com/sync, the OpenTogetherTube API responds with not finding "sync"
`Cannot GET /sync`

Is there a way to let the nodejs server use the /sync URI as its root, or is that just not viable?

**Comment by dyc3** [comment]
Setting a base URI is not possible (right now at least). If you're hosting multiple things on the same domain, the easiest solution would be to use a subdomain.

**Comment by RandomWolf** [comment]
Ah, thats too bad. Thank you regardless!
