### ISSUE TITLE
configure-room.set-queue-mode not changeable

### ISSUE THREAD

**Issue by LeonPro12** [dyc3/opentogethertube#393]
## Current Behavior
You can't change the permissions for configure-room.set-queue-mode. In general the permissions seem buggy.

### How To Reproduce
Click on "Settings", and try to change "configure-room.set-queue-mode", then refresh the site.

**Comment by dyc3** [comment]
Thanks for reporting this. I'll see if I can take a look today. PRs always appreciated though.

> In general the permissions seem buggy.

Please file more bugs! I can't fix them if I don't know they exist.

**Comment by dyc3** [comment]
I tried it again today, and it appears to have fixed itself. Can you confirm? @LeonPro12

**Comment by LeonPro12** [comment]
The whole site seems to be non-functional.

**Comment by dyc3** [comment]
> The whole site seems to be non-functional.

Fixed. Cause unrelated to this issue. See #396.

**Comment by LeonPro12** [comment]
Nice, but it still has the same bug. Also, it switches from "vote" to "manual" every time.

**Comment by dyc3** [comment]
What is the name of the room you're using?

**Comment by LeonPro12** [comment]
> 
> 
> What is the name or URL of the room you're using? I'd like to check the logs to see what exactly is happening.

https://opentogethertube.com/room/ProServer

**Comment by dyc3** [comment]
I don't see anything wrong in the logs, and I'm having trouble reproducing the issue. Would you mind making a screen recording reproducing the issue, showing exactly what happens?

**Comment by dyc3** [comment]
I'm going to close this issue for now, since it seems to be fixed. If it happens again, feel free to let me know, and please include a screen recording.
