### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#40]
The original togethertube had a chat feature that also served as an event log.

Users could send messages in the chat so other users in the room could see them. This chat box also doubled as an event log, meaning it would show messages like "[USER] joined the room", "[USER] skipped [VIDEO TITLE]", or "[USER] skipped to 3:25".

**Comment by carpenterd777** [comment]
I know this feature has already been merged, but I forgot to ask about how it plays with fullscreen. Now that chat takes up a good portion of the window, putting the video on fullscreen does not allow the video to take up the user's entire display. Should we move the chat box when the user is in fullscreen?
