### ISSUE TITLE
Can't add video to temporary room

### ISSUE THREAD

**Issue by maddie-wang** [dyc3/opentogethertube#407]
## Current Behavior
I can't add a video to a temporary room after sitting in there for 20-30 mins. After I click add, it turns the [+] icon to [!]. This issue has been preventing me and 70 other users on my site from using OTT.

Possible Cause: I think the temporary room expired, which is why it bugs out when I try to add a video to it. When I visit that bugged OTT room on another tab, it says "Room not found." Maybe the socket disconnected me, or server restarted.

### How To Reproduce
1. I sat in a room on sesame, talked with friends for awhile. (Eg: https://www.sesamecall.com/call/?room=d1ee35ec) 
2. I tried adding a video and it gave me this POST error: `xhr.js:177 POST https://opentogethertube.com/api/room/d1ee35ec2e914e27ac822777160e0c94/queue 404`

## Expected behavior
1. I can add a video to a room. If for some reason the room is expired, it will be recreated.

### Screenshots
![image](https://user-images.githubusercontent.com/32725368/117081966-a388e980-ad06-11eb-82fc-929e19bb64ef.png)

## Environment
- [ X ] This happens on the partner site which uses an iframe of OTT: https://www.sesamecall.com

### Desktop (please complete the following information when applicable):
 - OS: iOS
 - Browser: Chrome

@dyc3  Thanks for helping me before! Do you mind looking into this one? Many users are not able to use OTT in call due to this bug.

**Comment by dyc3** [comment]
404 means the room is not found. If the room is empty for a certain amount amount of time, the room gets unloaded, and all of the room state is lost. Room state is preserved across server restarts. I don't see anything weird in the logs for that room.

Heroku likes to disconnect my websockets for some reason (even though im sending messages to keep the connection alive), but the client should reconnect automatically. When this happens, does "Connecting..." appear above the video?

**Comment by dyc3** [comment]
Hey @maddie-wang, are you still having this problem?

**Comment by dyc3** [comment]
I'm closing this as stale. Let me know if it's still an issue.

**Comment by maddie-wang** [comment]
@dyc3 I'm still having this issue! For example, try adding a video at this link: https://opentogethertube.com/room/2F814828dd4102447085edc88cd634049e

**Comment by maddie-wang** [comment]
Yes, it has "Connecting..." at the top!

**Comment by dyc3** [comment]
OTT does not recreate temporary rooms after they have been unloaded. Once they are unloaded, they are gone forever. If a client tries to join a room that does not exist, then it gets disconnected by the server. At the time of writing, there is a bug that prevents the client from knowing whether or not a room exists, so it will just keep trying to reconnect.
