### ISSUE TITLE
permanent room does not keep room creator as the admin of that room

### ISSUE THREAD

**Issue by LividJava** [dyc3/opentogethertube#408]
I'm not quite sure what the exact issue is here, but awhile ago i logged on with my discord account and created a room. It does not keep me as the room owner when viewing the room and logging back in.

As far as I am aware there is no way to recover ownership of the room

**Comment by dyc3** [comment]
What's the name of the room (its shown in the URL), and what is your discord user ID (should be a bunch of numbers, not your username and discriminator)?

**Comment by LividJava** [comment]
The issue appears to have cleared itself up... not sure when or how... but i was able to claim the room
