### ISSUE TITLE
Shuffle Button

### ISSUE THREAD

**Issue by tututuana** [dyc3/opentogethertube#418]
**Is your feature request related to a problem? Please describe.**
When we listen to songs with my friend, we usually add them from a playlist and it gets boring after a while to always listen in the same order, so I would be glad if you add a shuffle button to the video list.

**Describe the solution you'd like**
Shuffle button to the video list

**Comment by tututuana** [comment]
is it still in work?

**Comment by dyc3** [comment]
I haven't quite gotten around to doing this yet, I can't give an exact timeline. I'm open to pull requests though.
