### ISSUE TITLE
Room settings are not loaded from database

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#426]
## Current Behavior

Room settings like room name, room description, visibility and room queue are unfortunately not loaded.

If you set something in the permanent room and then come back to the permanent room when it is inactive, all settings (except permissions) are gone.

## Expected behavior

Room settings should be loaded from database again

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Confirmed, I was able to reproduce this issue.

**Comment by Sebasee009** [comment]
Ok :)

**Comment by dyc3** [comment]
After investigating, I think it's an upstream bug in sequelize. It's strange because it only appears that title, description, visibility, and queueMode are affected.

**Comment by Sebasee009** [comment]
Yes that is really strange

**Comment by dyc3** [comment]
I think I found the issue. In `models/room.ts`, the Room class sets default values for the affected fields, but not the others.
