### ISSUE TITLE
Docker image never healthy

### ISSUE THREAD

**Issue by XeroxDev** [dyc3/opentogethertube#436]
## Current Behavior
After the "health: starting" state, it goes directly into unhealthy state. It never is in healthy state.
Health check may be broken?

### How To Reproduce
1. Get docker-compose.yml file from repository (root one)
2. Let the containers get pulled or updated.
3. Execute ```docker-compose -f docker-compose.yml --env-file env/production.env up -d --build```
4. Execute ```watch -n 1 docker ps -a```
5. See all health states.
You may see something like this:
```
Every 1.0s: docker ps -a                                                                                                                            kanade.xeroxdev.de: Mon May 31 16:47:55 2021

CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                     PORTS                                       NAMES
28921b2c74f7   dyc3/opentogethertube:latest   "docker-entrypoint.s…"   10 minutes ago   Up 9 minutes (unhealthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   opentogethertube
cebf1e04c222   postgres                       "docker-entrypoint.s…"   6 weeks ago      Up 9 minutes (healthy)     5432/tcp                                    opentogethertube_postgres
9bb193e2fc6a   redis                          "docker-entrypoint.s…"   6 weeks ago      Up 9 minutes (healthy)     6379/tcp                                    opentogethertube_redis
```
## Expected behavior
Should show the current health state and not always "unhealthy".

## Environment
- [ ] This happens on the official site: opentogethertube.com
- [X] This happens using a self-hosted version.
    - [X] I'm using the docker image.

#### Additional context
This is no breaking bug nor a important one. But I would be happy to see this fixed.

**Comment by dyc3** [comment]
Confirmed, I was able to reproduce this.

**Comment by dyc3** [comment]
This is weird because there doesn't seem to be anything wrong with the health check. I'm not really sure what's wrong with it.

**Comment by XeroxDev** [comment]
Unfortunately, I can only guess at the moment. But my guess is that the healthcheck is missing in the docker-compose.yml file. It will probably be carried out somewhere else, because otherwise there would be no healthcheck, but redis and postgres has the "healthcheck" variable and opentogethertube not.
