### ISSUE TITLE
Skip/next video doesn't work

### ISSUE THREAD

**Issue by maddie-wang** [dyc3/opentogethertube#438]
## Current Behavior
Can't click "Skip/Next video" button

### How To Reproduce
1. Create permanent room (my room is called: sesame)
2. Click skip/next video
3. Nothing happens
4. Even if the video ends, it wont go to the next video

## Expected behavior
Clicking the skip/next button should go to the next video. When the video ends, it should go to the next video.

### Screenshots
![image](https://user-images.githubusercontent.com/32725368/120236191-56bf0280-c221-11eb-87c4-fbe16d853f3f.png)

## Environment

- [ X ] This happens on the official site: opentogethertube.com on iframe (Sesamecall.com)

### Desktop (please complete the following information when applicable):
 - OS: iOS
 - Browser: Chrome

@dyc3

**Comment by dyc3** [comment]
I am not able to reproduce this. However, this behavior can occur if the client is not actually connected.
