### ISSUE TITLE
Searching "lofi" does not work in OTT

### ISSUE THREAD

**Issue by maddie-wang** [dyc3/opentogethertube#439]
## Current Behavior
Searching up "lofi" when you're adding videos leads to error message

### How To Reproduce
1. Create permanent room (my room is called: sesame)
2. Search up lofi
3. Error message appears

## Expected behavior
Searching up lofi should give a list of videos that appear
NOTE: searching up lofi2 seems to work, but not lofi

### Screenshots
![image](https://user-images.githubusercontent.com/32725368/120238276-e5cc1a80-c221-11eb-8f31-90b6bdc61341.png)

## Environment

- [ X ] This happens on the official site: opentogethertube.com on iframe (Sesamecall.com)

### Desktop (please complete the following information when applicable):
 - OS: iOS
 - Browser: Chrome

@dyc3

**Comment by dyc3** [comment]
Confirmed, able to reproduce

**Comment by dyc3** [comment]
This is caused by trying to parse the duration of a livestream, which has a duration with the value `P0D`. IIRC, OTT shouldn't be getting those in api responses anyway.
