### ISSUE TITLE
Join Bug

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#442]
## Current Behavior

This bug occurs 3 problems.
1. when you connect to a room that already has a video running, you can't skip the video. (#438)
2. when you create or join a room, you can't add a video.  (Unregistered User)
3. if you pause a video and then disconnect the room, and then the room is inactive, then rejoin the room the video is still there. (Permanent Room)

## Expected behavior

There should be no problems when joining

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Is this 3 different bugs?
