### ISSUE TITLE
Room inactivity bug

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#452]
## Current Behavior

if you add and pause a video and then disconnect the room, and then the room is inactive, then rejoin the room the video is still there.

### How To Reproduce

1. Create or Join the room
2. Add a video
3. Leave the room until the inactive
4. Rejoin the room and the video is still there

## Expected behavior

When the room is inactive the video should already be removed.

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by dyc3** [comment]
It takes ~5 minutes for a room to be unloaded. Can you post logs?

**Comment by Sebasee009** [comment]
Sorry I have no logs

**Comment by dyc3** [comment]
Oh, idk why but I thought you were using the self-hosted version. What's the room name so I can look at the logs?

**Comment by Sebasee009** [comment]
My room name is sebasee009.
I liked using the opentogethertube.com site, it has become my favorite site :)

**Comment by Sebasee009** [comment]
Oh this bug is seen in the rooms page.
https://opentogethertube.com/rooms

**Comment by dyc3** [comment]
Ah, so rooms are not getting unloaded for some reason

**Comment by Sebasee009** [comment]
Hi there is still a problem that when a video pausing leave in and then the permanent space is inactive, come back in the video is still there.
