### ISSUE TITLE
First video added to the queue doesn't show up in the queue

### ISSUE THREAD

**Issue by tortured1** [dyc3/opentogethertube#463]
## Current Behavior

The first video added doesn't show up in the queue, but the back-end thinks it's there.

### How To Reproduce

1. Go to the "Add" tab.
2. Paste in video URL
3. click on the "check" mark
4. Wait for the countdowns to complete.
5. Look at the queue.  It's empty (and shows 0 length)
6. Go back to the "Add" tab, click on the "check" mark in the video
7. The error appears
 
Additional notes:
If another video is added, that one shows up in the queue, but the above added video is the one that plays.

## Expected behavior

The video should be added to the queue.

### Screenshots
![image](https://user-images.githubusercontent.com/24273100/126051337-7e88387e-b97c-4be3-9832-3ee13dacb0c7.png)

## Environment

- [X] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

### Desktop (please complete the following information when applicable):
 - OS: Fedora 34
 - Browser: Chrome
 - Version: 91.0.4472.164
 -

**Comment by tortured1** [comment]
Here's what the queue looks like after adding a second video.  Note the runtime in the playing video is that of the first movie added... 
![image](https://user-images.githubusercontent.com/24273100/126051384-04050085-47cd-414e-929f-02ae209d2b6a.png)

**Comment by dyc3** [comment]
This is intentional behavior. When the queue is empty and no video is playing, adding a video to the queue just makes it the video that is currently playing.
