### ISSUE TITLE
Unhandled exception when getting video: TypeError

### ISSUE THREAD

**Issue by TubaApollo** [dyc3/opentogethertube#471]
Unfortunately there is no Apache Config for OTT, I have tried to create my own config but as soon as I add a video I get the following Error:
```
2021-08-20 16:51:17 api error Unhandled exception when getting video: TypeError: Cannot read property 'id' of null TypeError: Cannot read property 'id' of null
    at Room.getRoleFromToken (/root/opentogethertube/server/room.ts:331:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Room.processRequest (/root/opentogethertube/server/room.ts:546:22)
    at /root/opentogethertube/api.js:233:3
```
My Apache Config looks like this:
```
<VirtualHost *:80 >
	ServerName "<domain>"
	DocumentRoot "/var/www/<domain>"
	CustomLog "/var/log/apache2/<domain>.access.log" combined
	ErrorLog "/var/log/apache2/<domain>.error.log"
	UseCanonicalName Off
	TimeOut 180000
	LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
	LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
	LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
	ProxyPreserveHost On
	        SSLProxyEngine On
	        ProxyPass / http://localhost:3000/
	        ProxyPassReverse / http://localhost:3000/
	        RewriteEngine on
	        RewriteCond %{HTTP:Upgrade} websocket [NC]
	        RewriteCond %{HTTP:Connection} upgrade [NC]
	        RewriteRule .* ws://localhost:3000%{REQUEST_URI} [P]
	Alias "/.well-known/acme-challenge" "/opt/domains/<domain>/letsencrypt/challenges"
	<Directory "/opt/domains/<domain>/letsencrypt/challenges">
		Options None
		AllowOverride None
		Order allow,deny
		Allow from all
		Require all granted
		ForceType text/plain
		DirectoryIndex disabled
	</Directory>
	<Directory "/var/www/<domain>" >
		AllowOverride All
		Options Includes FollowSymLinks
	</Directory>
	<IfModule mod_rewrite.c>
		RewriteEngine On
		RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
		RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
	</IfModule>
	<IfModule mod_http2.c>
		Protocols h2 h2c http/1.1
	</IfModule>

</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443 >
	ServerName "<domain>"
	DocumentRoot "/var/www/<domain>"
	CustomLog "/var/log/apache2/<domain>.access.log" combined
	ErrorLog "/var/log/apache2/<domain>.error.log"
	UseCanonicalName Off
	TimeOut 180000
	LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
	LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
	LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
	ProxyPreserveHost On
	        SSLProxyEngine On
	        ProxyPass / http://localhost:3000/
	        ProxyPassReverse / http://localhost:3000/
	        RewriteEngine on
	        RewriteCond %{HTTP:Upgrade} websocket [NC]
	        RewriteCond %{HTTP:Connection} upgrade [NC]
	        RewriteRule .* ws://localhost:3000%{REQUEST_URI} [P]
	<IfModule mod_rewrite.c>
		RewriteEngine On
		RewriteCond %{REQUEST_URI} ^/\.well\-known/acme\-challenge/
		RewriteRule (.*) http://%{HTTP_HOST}%{REQUEST_URI}
	</IfModule>
	<Directory "/var/www/<domain>" >
		AllowOverride All
		Options Includes FollowSymLinks
	</Directory>
	SSLEngine on
	SSLCertificateFile /opt/domains/<domain>/ssl/ssl-letsencrypt.crt
	SSLCertificateKeyFile /opt/domains/<domain>/ssl/ssl-letsencrypt.key
	SSLCertificateChainFile /opt/domains/<domain>/ssl/ssl-letsencrypt.ca
	SSLUseStapling on
	SSLProtocol all -SSLv2 -SSLv3
	SSLHonorCipherOrder on
	SSLCipherSuite "ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-ECDSA-AES128-SHA256 ECDHE-RSA-AES128-SHA256 EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS"

	Header set Strict-Transport-Security "max-age=600; preload"

	<IfModule mod_http2.c>
		Protocols h2 h2c http/1.1
	</IfModule>
```
When I access OTT over the IP, there are no problems.

**Comment by dyc3** [comment]
Hey, thanks for opening an issue. I need a little more info in order to determine what's going on.

1. Are you using the docker container?
2. In your browser's localstorage, is there a `token` present (for both accessing over IP and via your domain)?
3. Check the network tab in your browser's devtools, and reload the page. Is there a request to `/api/auth/grant`?
4. Check the network tab in your browser's devtools, and try to add a video. Is there an `Authorization` header in the request? Does the value contain the token?

**Comment by TubaApollo** [comment]
Thanks for the fast Response!
1. No, I do not use the Docker Container.
2. Yes, for both is a token present.
3. If "grant" is /api/auth/grant/ then it does a request to /api/auth/grant/ (Domain and IP).
4. Seems not like i have an Authorization header in the request, but i´m not completely sure because i didnt see anything in the Network Log as well over the IP.
I also see that every Action (Delete etc.) does not work over the Domain. In the Browser Console comes this error:
`POST https://<domain>/api/room/3899668b-ac2f-4046-8f1a-dfcdb6d85dc1/queue 500                                xhr.js:177`

**Comment by TubaApollo** [comment]
I have the problem, it's because I'm logged in, it is working fine also with the Domain as soon as i log out, so it's probably not the Apache config at all.

**Comment by dyc3** [comment]
Can you give me some specific steps to reproduce what you are seeing?

**Comment by TubaApollo** [comment]
My Operating System is `Ubuntu 20.04` i installed OTT with Setup Instructions Step by Step without Problems (but i got a lot, really a lot of warns during the installation) , i use `npm --version
7.21.0` and `node --version v12.22.5` after installing it and setting up the Proxy it works fine without the Login. As soon as i register a Account and Login, i can not write in the Chat can not add Videos etc., everytime i try to make a Action i get the Error in the Console, it seems like OTT does not recognise the user.
I have a Video uploaded to better understand the problem: https://tubaapollo.de/media/ott.mp4

**Comment by dyc3** [comment]
If you refresh the page, do you stay logged in? I think this might be a problem with redis not saving the session state.

**Comment by dyc3** [comment]
Ah, ok so this happens for unowned rooms.

**Comment by dyc3** [comment]
Should be fixed, feel free to reopen if its not
