### ISSUE TITLE
First vote for video casts multiple votes

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#508]
## Current Behavior

This vote mode is unfortunately buggy,
When I set this, the videos are not displayed directly but later. The vote button unfortunately also does not quite work, and I can vote 3 times although that should not be so.

### How To Reproduce

1. Add a Video
2. Add another Video
3. Switch to Queue
4. See this Bug

## Expected behavior

It should work as it did before.

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by dyc3** [comment]
I can reproduce this. lol whoops. I'll try and fix it today.

**Comment by dyc3** [comment]
I can't seem to reproduce it locally though. Very strange...

**Comment by dyc3** [comment]
I was able to figure out what was happening. For example, if the client ID is `"12"`, then voting for the first time on a video would add a vote for each char in the string, so `"1"` and `"2"`. Will fix shortly.
