### ISSUE TITLE
Video add preview is not cleared immediately when the text in the textbox changes 

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#511]
## Current Behavior

The preview box, if you remove the URL manually it's still there, or if you add a video then drag and drop the URL into the textbox then the buttons are still there from the previous video, because the preview box was not removed before.  Unfortunately, this is somehow misleading.

## Expected behavior

The preview box should automatically remove when you do that.

## Environment

- [x] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Can you post a video of what you are talking about? I'm having trouble reproducing this.

**Comment by Sebasee009** [comment]
So here I have made a short video in which you can see the bug

https://www.youtube.com/watch?v=IAfxeokV8D8

**Comment by dyc3** [comment]
Ah, ok. I'll change the title to be a little more specific.
