### ISSUE TITLE
Feature Request: m3u Support

### ISSUE THREAD

**Issue by Kippenhof** [dyc3/opentogethertube#518]
**Is your feature request related to a problem? Please describe.**
I can't use Open Together Tube for watching .m3u or .m3u8 Files

**Describe the solution you'd like**
Support for adding and Watching m3u/m3u8 Files

**Describe alternatives you've considered**
Download the Files and Upload it to an Webserver, but it takes a lot of time on long Files

**Additional context**
I love the App, thx for everything.

**Comment by dyc3** [comment]
Managed to figure it out, adding the `-show_format` argument provides some extra info, and includes duration.

**Comment by Kippenhof** [comment]
Thats awesome, thx :)
