### ISSUE TITLE
OPENTOGETHERTUBE_API_KEY is invalid.

### ISSUE THREAD

**Issue by Vibeshibe** [dyc3/opentogethertube#519]
Hiya,

I've been meaning to try hosting OTT using docker compose, I cloned the repo and setup the production.env with my API keys. 

There I encountered the issue in the OTT container that it can't validate the config file because the OTT API Key is invalid. I left it as standard the first time I ran (GENERATE_YOUR_OWN) which I first saw as the possible issue here but next time I tried inputting a self generated key and secret, which resulted in the same error. I tried building from scratch and did everything from 0 but no matter what I do the container keeps restarting because OTT API Key supposedly isn't valid.

I've added the logs from the container as a attachement to this issue.
[_opentogethertube_logs.txt](https://github.com/dyc3/opentogethertube/files/7277877/_opentogethertube_logs.txt)

**Comment by dyc3** [comment]
There's a hard restriction that the OTT API key must be at least 40 characters long.

https://github.com/dyc3/opentogethertube/blob/ca264666ef035cf11cb47415666c075869b7584c/app.js#L45

OTT's configuration is an open problem that I haven't had the chance to look into deeper yet. See: #349

**Comment by Vibeshibe** [comment]
Yup. Was actually the issue that my API key was only 36 characters. Thanks for the help! I'll close this issue now.
