### ISSUE TITLE
The videos are not displayed in the queue when you set the vote mode.

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#522]
### Current Behavior

When you joint or create the room and set the vote mode, then add some videos, the queue is not displayed directly.

### Expected Behavior

When you set the vote mode, you should see the videos in the queue.

### Steps To Reproduce

1. Join or create a room
2. Set vote mode
3. add a few videos
4. switch to queue

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by FriedrichGaming** [comment]
@Sebasee009 This was probably the same bug i encountered in #532. It should be fixed now.
