### ISSUE TITLE
Video player bug

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#540]
### Current Behavior

Video player always detects that a video is inside although that is not so and if you forgot to skip a video when I leave is displayed again even after inactivity, that is also only seen in permanent room
![Screenshot OTT 2021-10-16 170742](https://user-images.githubusercontent.com/14842479/137592632-5efeb439-a45e-499e-99e9-f6ba3d459d25.jpg)

### Expected Behavior

Video player is supposed to when there is no video inside that also can't do any actions and also can't show video after inactivity.

### Steps To Reproduce

1. create or join permanent room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
I'm not sure what the bug here is. Is it that the video controls are visible when there is no video?
