### ISSUE TITLE
when changing the username as an unregistered user is not changed in the user list

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#553]
### Current Behavior

when changing the username as an unregistered user is not changed in the user list

### Expected Behavior

if you change the username as an unregistered user, the user list should be changed as well

### Steps To Reproduce

1. create or join room
2. edit username

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
I was able to recreate this issue in prod.
