### ISSUE TITLE
Sometimes, the next video does not get dequeued immediately when the current video ends.

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#558]
### Expected Behavior

When the current video ends, the next video should always get dequeued to become the current video.

### Steps To Reproduce

Precise steps unknown. Seems to occur only in production.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

This also makes other controls somewhat unresponsive.

There could be a couple things that are happening:
- High load is causing a big queue in the event loop because of all the room updates?
    - Need to observe metrics when the bug occurs next time
- Maybe sponsorblock requests are blocking dequeuing?
    - There's no protection for making multiple concurrent requests for the same video's segments, which could be problematic.

**Comment by xRealNeon** [comment]
IDK how the queue works, but maybe remove the video from the queue when it starts playing?

**Comment by dyc3** [comment]
This seems to not be a problem anymore. Closing as fixed.
