### ISSUE TITLE
Playback control disappears when pausing a video moments before it ends

### ISSUE THREAD

**Issue by FriedrichGaming** [dyc3/opentogethertube#561]
### Current Behavior

https://user-images.githubusercontent.com/50049702/142931993-7a5566da-d489-4aad-a524-4672b502294d.mp4

### Expected Behavior

Playback control shouldn't disappear

### Steps To Reproduce

1. Create a Room
2. Add some Videos to the Queue
3. Skip to a point near to the end of the current Video
4. Play the Video and pause at the last possible moment before the video ends

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Yeah, I've encountered this a couple times, thanks for finding something reproducible! As a workaround, you should be able to hit spacebar to toggle playback, like a normal video player.

**Comment by dyc3** [comment]
I'm actually having some trouble reproducing this on my end. I did exactly what you did in the video. What browser and OS are you using? Include the version numbers please.

**Comment by FriedrichGaming** [comment]
OS: Fedora Linux 35
Browser: Firefox 94.0 (RPM Package) & Brave 1.32.106 (Flatpak)

> Can you reproduce it without any browser extensions?

Yes

**Comment by dyc3** [comment]
I've added a keyboard shortcut to enable debug mode in production: `ctrl+shift+F12`. It's currently being deployed, but it should be done in about 5 minutes. Can you record a new video with that panel visible? It's on the right side, under chat, says "Debug" at the top. Make sure the "Video controls" item is in that list.

**Comment by FriedrichGaming** [comment]
Debug mode was already enabled by default.

https://user-images.githubusercontent.com/50049702/143063542-5e756aa2-0d46-4330-9f3c-f38cf3076a35.mp4

**Comment by dyc3** [comment]
My current theory is that something is happening that's causing the mousemove events to disappear. But it fixes itself when you go to the next video, so that doesn't really make much sense tbh...

I was able to actually reproduce it just now. I'll be able to investigate this better
