### ISSUE TITLE
Play now button next to the add to queue button

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#613]
### Is your feature request related to a problem? Please describe.

You have to click on the submenu to play a video without the queue

### Describe the solution you'd like

It would be cool if the play now button is next to the add to queue button and not in a submenu.

### Additional context

![grafik](https://user-images.githubusercontent.com/20997346/152517072-15ac6e9e-2f62-4446-990f-50d180ffba43.png)

**Comment by dyc3** [comment]
If there is no video playing, adding the video to the queue will start the video. In other words, when there is no video playing, add to queue and play now effectively do the same thing. When there *is* a video playing, play now pushes the current video into the top of the queue, and replaces the current video with the new one.

You mentioned that you don't want to use the queue to play a video. Could you elaborate a little bit more? I'd like to pin down what kind of UI issue this is. Is the UI not clear or is this simply desired for convenience?

**Comment by xRealNeon** [comment]
I think it's more convenient than clicking on the three dots and then the button.
