### ISSUE TITLE
Warning while building

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#615]
### Current Behavior

Throws a lot of deprecation errors while building.

### Expected Behavior

Shouldn’t do that.

### Steps To Reproduce

1. Clone
2. `yarn`
3. `yarn build`

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

![grafik](https://user-images.githubusercontent.com/20997346/152600572-dc1f86c3-3285-4001-8c53-f44d1ba01233.png)
![grafik](https://user-images.githubusercontent.com/20997346/152600599-42d561c6-7e77-474d-a490-cf8ad100aa5e.png)

**Comment by dyc3** [comment]
Yeah this is not really my fault. It's an upstream problem in vuetify: https://github.com/vuetifyjs/vuetify/issues/13694#issuecomment-907768247

It'll be fixed when we upgrade to vuetify 3, but its not stable yet. They're just deprecation warnings, it won't break if we don't change dependency versions.
