### ISSUE TITLE
German Localization

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#616]
### Is your feature request related to a problem? Please describe.

Localization

### Describe the solution you'd like

- Adding all strings in the ui to the lang file
- How can a user change the language?
- I can add the missing strings and make a German translation

**Comment by dyc3** [comment]
Thanks for your interest, that would be _super_ awesome! I should probably write some docs for how to add new languages.

There's no UI for switching languages yet (on my todo list). You should be able to add a file called `de.ts` to `client/src/locales/` and as long as you match the schema of `en.ts` it should work. As a temporary thing while developing, you should be able to use the environment variable `VUE_APP_I18N_LOCALE` to set the language.

If you're going to work on this, please separate this in to 2 different PRs:
1. Adding all the remaining strings to `en.ts`
2. Adding German.

**Comment by xRealNeon** [comment]
How do I translate text with links or something like this. @dyc3 

![grafik](https://user-images.githubusercontent.com/20997346/152616543-945be980-98a7-4832-aa34-066bb037fb23.png)

**Comment by xRealNeon** [comment]
I think I should do it like described here: https://vue-i18n.intlify.dev/guide/advanced/component.html

**Comment by xRealNeon** [comment]
but with texts with a lot of new lines this would also be impractical.

**Comment by dyc3** [comment]
Tbh, I'm not completely sure about the best approach. But that article you linked seems pretty good

**Comment by xRealNeon** [comment]
Where are the usernames generated?

**Comment by dyc3** [comment]
> Where are the usernames generated?

They are generated using the `unique-names-generator` package, ctrl + f around for that.

> Is it a good idea to use localized usernames?

No, probably not.

**Comment by dyc3** [comment]
Hey @xRealNeon, hows this coming along?

**Comment by dyc3** [comment]
Unassigned for inactivity

**Comment by dyc3** [comment]
Closing as completed
