### ISSUE TITLE
Two different Full screen modes

### ISSUE THREAD

**Issue by xRealNeon** [dyc3/opentogethertube#619]
### Current Behavior

When I click on the full screen button, I get the "right" full screen, but when I double-click on the video, I get the normal YouTube full screen.

### Expected Behavior

When I double-click, the "right" full screen mode should open.

### Steps To Reproduce

Double-click in the video player.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This is expected behavior, and not really much I can do about without compromising being able to interact with the YouTube player.
