### ISSUE TITLE
Urgend: Site is not Availible

### ISSUE THREAD

**Issue by hofq** [dyc3/opentogethertube#620]
### Current Behavior

![grafik](https://user-images.githubusercontent.com/54744977/152660948-da3d04e4-d45d-497c-b09e-b2b4228073c8.png)

### Expected Behavior

The site should come up

### Steps To Reproduce

1. Open the URL
2. Ge the Error
Not on Staging, just on Prod

### Environment

- [x] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

it was working a few minutes ago

**Comment by hofq** [comment]
it's back

**Comment by dyc3** [comment]
I'll look into this a bit more, there were a lot of app crashes.

![image](https://user-images.githubusercontent.com/1808807/152662676-5baf4cfb-b31e-4087-a87d-e16a526df373.png)
