### ISSUE TITLE
Chat in Fullscreen Mode

### ISSUE THREAD

**Issue by Shu2ik** [dyc3/opentogethertube#622]
### Is your feature request related to a problem? Please describe.

OpenTogetherTube is almost the perfect replacement for Metastream.
Unfortunately there's no way to use or see the chat in full-screen mode for the best experience.

### Describe the solution you'd like

I would like to use the chat function in full-screen video mode like it's happening in Metastream with an overlay box you make appear by pressing Enter on the keyboard. Would it be possible to implement that feature?

**Comment by xInstead** [comment]
Everything feels so right about the site and how it works, but why oh why can't you use the chat feature in full-screen mode. This is so vexing. When I thought I found the perfect site for my needs, it misses that one feature to deliver the utmost experience...

If an overlay chat box doesn't work out then a collapsible sidebar with a notification hint for new messages when it's collapsed would be fine as well.

**Comment by Shu2ik** [comment]
PR as in promotion? I'm seriously willing to drop 50-100$ for that feature

**Comment by dyc3** [comment]
No, PR as in pull request.

**Comment by Shu2ik** [comment]
If I needed to be versed in the material for that, I don't think I might be able to help much

**Comment by Shu2ik** [comment]
Alright, thank you. 
I will check it out later and leave some thoughts on it.

**Comment by Shu2ik** [comment]
With 'deployed' do you mean implemented? Because I don't see any changes.

**Comment by Shu2ik** [comment]
It feels nice seeing the chat window in fullscreen now for starters.

As ultimate goal it would be great if it also worked in an unobtrusive way. So being able to open/close it but also don't miss out on comments when it's collapsed. I don't have a specific wish how it should look or work as long as it works as a feature, I would be happy it. Seeing how those boxes pop up when playback controls are used made me think it might be possible to do the same with comments but just leave them a little longer on screen. I would  also be fine with opening chat manually after seeing a badge for example telling me there's a new comment. So whatever is easy for you to implement without breaking the site would be totally fine.

**Comment by Shu2ik** [comment]
Seeing how much free space the player bar has to the right made me think that the following concept would be quite a convenient and comfortable solution.

Typing into the bar and make comments float onto the video. 
Furthermore you could open and show the chat box with a drop-up menu. 

Not sure how realistic it is to implement but it strikes to me as a very round and clean feature.

![fullscreen chat 1](https://user-images.githubusercontent.com/31248913/153773020-b3b3cbc5-8398-403c-9428-a572a55df0ba.jpg)

![fullscreen chat 2](https://user-images.githubusercontent.com/31248913/153773023-fda42061-84ab-4d32-9bae-d92b1d39255d.jpg)

**Comment by Shu2ik** [comment]
Sorry that I keep nagging...
Just want to get the rest of the ideas/suggestions out of my head.

It would be a nice and seamless experience if you could do the whole thing without mouse involvement or input, like focusing and releasing the type field by pressing Enter. Pressing Enter in an empty field would release it as well. And to top it all, assigning a hotkey to open/close the chat box.

**Comment by Shu2ik** [comment]
How is it progressing so far? Any successful steps to report?
I don't mean to put any pressure up. Just being curious if there's something to look forward to already.

**Comment by dyc3** [comment]
Sorry, I'm mostly busy with schoolwork at the moment. It might take a while.

**Comment by Shu2ik** [comment]
Alright, no problem.
Take your time.

**Comment by dyc3** [comment]
See #631 for updates on the chat rework
