### ISSUE TITLE
Vimeo videos are broken

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#640]
### Current Behavior

Vimeo videos will not play. They just get stuck on the video thumbnail.

Add preview thumbnails for vimeo videos are also broken.

### Expected Behavior

Vimeo videos should play

### Steps To Reproduce

1. Play a vimeo video

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by Kit-p** [comment]
@dyc3 Vimeo videos play just fine for me (on both Chromium and Firefox), is this issue still relevant?

**Comment by dyc3** [comment]
Yeah I just tried to reproduce this and I wasn't able to. I guess the vimeo player is just kinda flakey.
