### ISSUE TITLE
JS for each pattern instead of looping by index

### ISSUE THREAD

**Issue by adapap** [dyc3/opentogethertube#65]
https://github.com/dyc3/opentogethertube/blob/e15561900a576ff45adee93cd323a4fd90a7c2b1/infoextract.js#L72-L89

Javascript has two enumeration keywords that can be used in for loops: `in` and `of`
The former is used to enumerate by index for arrays or keys in objects, and the latter can be used to iterate through an object, such as values of an array.

I propose enforcing the use of [for .. of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) to increase readability/reduce redundancy in code. I am merely using the above as an example; there are many occurrences of the same construct.

```
for (let r = 0; r < regexs.length; r++) { 
    let matches = res.data.match(regexs[r]); 
    ... 
```
This can be replaced with:
```
for (let regex of regexs) {
    let matches = res.data.match(regex);
    ...
```

**Comment by dyc3** [comment]
I avoided using these keywords for 2 reasons. Firstly, I found `for ... in` and `for ... of` syntax confusing and actually less readable than just typical `for` syntax. Secondly, when writing a loop, if I suddenly wanted access to the index its available readily without needing to rewrite the `for` statement.

In this particular example, you can't replace
```
for (let r = 0; r < regexs.length; r++) { 
    let matches = res.data.match(regexs[r]); 
    ... 
```
because `r` is used later on line 82.

But I'd like to hear what others think.

**Comment by benwaffle** [comment]
use `for .. of` if you don't need the numerical index. don't use `for ... in` ever

**Comment by adapap** [comment]
Actually I disagree, `for .. in` can be used to loop through objects by key.

**Comment by benwaffle** [comment]
nah, you want `for (const key of Object.keys(obj))`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Why_Use_for...in

**Comment by ifkb99** [comment]
I think both ideas can be combined, in a way, for more readable and efficient code.

About halfway down, [this article](https://stackoverflow.blog/2019/09/12/practical-ways-to-write-better-javascript/) explains how basic for loops slow down code and increase complexity. With the forEach higher order function, you can still get the index along with completing the loop  asynchronously (this would obviously not work for sections that need to be completed sequentially).

The article does not mention how, but [according to mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) this loop could be refactored into
```js
regexes.forEach((regex, regIdx) => {
    let matches = regex //this line isnt even needed anymore
    ...
}
```

**Comment by ifkb99** [comment]
As another comment, 

```js
for (let r = 0; r < regexs.length; r++) {
    let matches = res.data.match(regexs[r]);
    if (matches == null) {
	continue;
    }
    for (let m = 0; m < matches.length; m++) {
	...
    }
}
```
can be simplified to
```js
for (let r = 0; r < regexs.length; r++) {
    let matches = res.data.match(regexs[r]);
    if (matches !== null) {
	for (let m = 0; m < matches.length; m++) {
	    ...
        }
    }
}
```

**Comment by dyc3** [comment]
@ifkb99 The purpose of using the pattern
```
if (matches == null) {
    continue;
}
...
```
instead of 
```
if (matches !== null) {
    ...
}
```
is to minimize the amount of indentation used. That way we don't get a bunch of tailing `}` like this
```
                    }
                }
            }
        }
    }
}
```
which gets harder to read at a certain point.

**Comment by dyc3** [comment]
During our scrum on 9/26, we decided that consistency was ideal, and that `for ... of` loops are easier to read. So we'll be actively refactoring our old `for` loops and replacing them with `for ... of`.
