### ISSUE TITLE
Userlist has weird behaviour after the same user joins room twice (and then leaves the room)

### ISSUE THREAD

**Issue by FriedrichGaming** [dyc3/opentogethertube#662]
### Current Behavior

![grafik](https://user-images.githubusercontent.com/50049702/160211535-ee49dd8c-7bd3-4ee0-98b1-b190c3658e08.png)

### Expected Behavior

![grafik](https://user-images.githubusercontent.com/50049702/160211562-9c6b79fc-836b-4630-a973-01e6ec99921a.png)

### Steps To Reproduce

1. Create a room
2. Invite some friends
3. Play video
4. Join room in a second browser tab (it has to be the same browser)
5. Leave Room in second browser tab

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Workaround: Press F5

**Comment by dyc3** [comment]
Confirmed: I was able to reproduce this.

**Comment by dyc3** [comment]
Is this still happening since the Vue 3 rewrite?

**Comment by FriedrichGaming** [comment]
No, this appears to no longer happen.
