### ISSUE TITLE
Blank page on mobile safari

### ISSUE THREAD

**Issue by gianklug** [dyc3/opentogethertube#668]
### Current Behavior

On the page for a room, instead of UI there is just a blank page with the OTT menu bar.

### Expected Behavior

The player and video shows up

### Steps To Reproduce

1. Open OTT
2. Join any room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

### Anything else?

Tested on an iPhone 11

**Comment by gianklug** [comment]
Could confirm it also using browserstack.com

Working Android:
![image](https://user-images.githubusercontent.com/51193103/167557544-bd862b9b-689e-49f8-bee1-13d652d25efa.png)

Not working iPhone:
![image](https://user-images.githubusercontent.com/51193103/167556818-49b3f0ae-0695-40f5-b5b8-fed529966234.png)

Not working iPad:
![image](https://user-images.githubusercontent.com/51193103/167557691-dbe82c8c-7ed5-4b3a-8418-c122f3b7a634.png)

**Comment by dyc3** [comment]
Well, I'll have to take your word for it. I don't have an apple device to test on.

**Comment by gianklug** [comment]
I can do some testing for you and maybe debug in some kind of developer tools if that'll help.

**Comment by dyc3** [comment]
If you could get me the console output, that would be super helpful.

**Comment by gianklug** [comment]
![76BA123A-39FE-428E-9651-EB94F606928A](https://user-images.githubusercontent.com/51193103/168315899-d24cd190-f6f3-48b3-9f4c-dc847e67fba9.jpeg)
In the chrome://inspect JavaScript console, i can see there errors popping up while trying to join a session. Sadly I can't debug any further than this as i don't have an iMac/MacBook for a full developer console.

**Comment by dyc3** [comment]
Ah, yeah it looks like that API is not supported on safari https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

**Comment by dyc3** [comment]
This functionally isn't necessary for the rest of the site to work. I'll canary a fix shortly so you can test it for me, and if it works I can merge it in and deploy it to the main site.

**Comment by dyc3** [comment]
I've found the second culprit. At the top of `Room.vue`, we have

```vue
<v-container
			fluid
			:class="{
				'room': true,
				'fullscreen': $store.state.fullscreen,
				'layout-default': $store.state.settings.roomLayout === RoomLayoutMode.default,
				'layout-theater': $store.state.settings.roomLayout === RoomLayoutMode.theater,
			}"
			v-if="!showJoinFailOverlay"
		>
```

For some reason, `RoomLayoutMode` is not defined in this context, only in safari.

**Comment by dyc3** [comment]
The problem is that I have no clue why _only safari_ is having this problem. Maybe there's a build option to replace all the enum values with their literals?

**Comment by gianklug** [comment]
As already stated in the PR, replacing `if(screen)` with `if(screen.orientation)` resolves the orientation issues for me and as far as i can tell (Will do some more testing afterwards) this resolves the issue completely for me.

If you want to i can create a PR of that.

**Comment by dyc3** [comment]
Perfect, go ahead and make a PR for that.

**Comment by gianklug** [comment]
> Perfect, go ahead and make a PR for that.

Done, please approve
