### ISSUE TITLE
Invidious Support

### ISSUE THREAD

**Issue by dejalavidavolar** [dyc3/opentogethertube#700]
### Is your feature request related to a problem? Please describe.

It' s not a problem.

### Describe the solution you'd like

Is there a way to add support to invidious? (https://invidious.io) It would be great!

Regards!

**Comment by dyc3** [comment]
FYI, you've used the wrong template. I would prefer if you use the "Service Support Request" template for this kind of request.

What do you mean by support? Invidious is just a front end for youtube, so all the videos on invidious can technically already be played by OTT. Do you mean just being able to parse invidious links?

**Comment by dyc3** [comment]
I'm closing this for being stale. It's been a year without updates.
