### ISSUE TITLE
Implementing Video settings (resolution,speed)

### ISSUE THREAD

**Issue by HerbertvandeBrick** [dyc3/opentogethertube#710]
### Is your feature request related to a problem? Please describe.

I´m always frustrated when i try to speed up the video i watch with my friends :-(

### Describe the solution you'd like

implementing the yt video settings button

### Additional context

I would like to support you with Bitcoin Lightning
Thanks for your work mate

**Comment by dyc3** [comment]
duplicate of #35, #569
