### ISSUE TITLE
Creating a permanent room with name which already exists causes ui to lock up.

### ISSUE THREAD

**Issue by naziks** [dyc3/opentogethertube#712]
### Current Behavior

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47501073/181925257-b518ef08-2a8c-4dbd-a1a6-08ddd37afab3.png">

### Expected Behavior

I expect to have an error with details (Error: Room with given name already exsts) in ui. But i can find it only in DevTools -> Network.

### Steps To Reproduce

1. Click create permament room
2. Type "onlyfans" in name
3. Click "Create room"

### Environment

- [X] This happens on the official site, opentogethertube.com
- [x] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Thank you!

**Comment by dyc3** [comment]
There seems to be a few bugs here:
- The overlay doesn't close when you click cancel
- The overlay doesn't go away when the request fails.
- The UI doesn't convey to the user that the room name already exists.
