### ISSUE TITLE
Bug: ffprobe not working on Docker distro

### ISSUE THREAD

**Issue by shindouj** [dyc3/opentogethertube#716]
### Current Behavior

On the newest Docker image available on Docker Registry, ffprobe is returning Input/output error for any URL I have been trying. 

### Expected Behavior

ffprobe returns correct data -> you are able to add an .mp4 successfully.

### Steps To Reproduce

1. Start a production Docker instance.
2. Try adding an .mp4 file hosted externally.

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

### Anything else?

After some investigation I have done this is caused by statically linked ffprobe not doing DNS resolution on Alpine Linux. Adding dynamically linked ffmpeg (apk add ffmpeg) to the Docker image and changing the path with environment variable it works like a charm.

If you decide this is indeed a bug and not only an issue I have experienced I will be more than happy to add a PR for you, too.

**Comment by shindouj** [comment]
@dyc3, could you please review the issue and let me know if you are alright with me issuing a PR fixing it?

**Comment by dyc3** [comment]
Yeah go for it.

**Comment by shindouj** [comment]
Confirming that #724 fixes the issue for Docker instances.
