### ISSUE TITLE
ffprobe is broken on heroku

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#722]
### Current Behavior

Unable to add movie by direct link

### Expected Behavior

Possibility to add a movie by direct link. Everything worked before. 

### Steps To Reproduce

1. Create room
2. Try paste link https://stream.voidboost.cc/895c4d74a8f87e000b53ab4d449d8928:2022092412:M1ZjNXJGNDgrbStic1h4MUFnQlQ5V3EzdEI1YkZ6RVozNEFaQWZDWjgyc3ZKNE1uMEpvWFk3OEtDbENWWngzU1hLR1BUTzJ3dXgxVkIybEJxdEtEUkE9PQ==/3/4/5/6/0/5/vh66h.mp4 in search
3. See error: Failed to get add preview. This is probably a bug, check console for details.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Console log:
```
Failed to get add preview Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    x xhr.js:66
AddPreview.vue:258
```
![изображение](https://user-images.githubusercontent.com/87234822/191978928-fe5976bd-0e61-4389-b767-44f03afef686.png)
![изображение](https://user-images.githubusercontent.com/87234822/191979073-cbbf6438-3092-413b-9610-3864768e71cb.png)
![изображение](https://user-images.githubusercontent.com/87234822/191979205-42bdfdd4-5ed9-45a7-99f1-94a7ba8646a8.png)
![изображение](https://user-images.githubusercontent.com/87234822/191979227-6b5fa081-daa9-4d61-82a7-9e4ef5b3e83e.png)
![изображение](https://user-images.githubusercontent.com/87234822/191979285-2b6192d9-59fd-4579-b97b-db0d073aadde.png)

**Comment by dyc3** [comment]
This is caused by ffprobe seg faulting when trying to grab the video's metadata. However, running ffprobe normally seems to not be a problem. This is probably a problem `@ffprobe-installer/ffprobe`, we might need to update it.

**Comment by dyc3** [comment]
I just tried manually updating ffprobe in heroku, and I'm getting the same seg fault. Something must have happened when I upgraded to `heroku-22`

**Comment by shindouj** [comment]
It is probably important to note that Heroku decided to stop supporting the free plan starting in November: https://blog.heroku.com/next-chapter

You might wanna consider moving the official instance somewhere else, unless you are using one of their paid plans.

**Comment by dyc3** [comment]
I'm aware, I'm using a paid dyno.

**Comment by dyc3** [comment]
Unfortunately, I don't think I'm able to fix ffprobe on short notice. I'll need to research an alternative.

**Comment by dyc3** [comment]
Just had an idea, what if OTT handles making the actual network request so that ffprobe doesn't need to do DNS resolution at all? I think I can get away with just piping the file into ffprobe's stdin

**Comment by shindouj** [comment]
So I obviously don't know how your deployments work on Heroku, but since #724 fixes this issue for Docker builds, you could temporarily get away with deploying the Docker image to your Dyno and run the app this way.

**Comment by dyc3** [comment]
My hunch was correct, piping to ffprobe works fine in bash. However, I can't seem to get it to work in node, and I really don't want to make `curl` a hard dependency for OTT. I'm going to have to come back to this later.

**Comment by SabatonShip** [comment]
![изображение](https://user-images.githubusercontent.com/87234822/192573229-7b0f11ab-983f-4daa-aad0-e477e1f35b3b.png)

**Comment by SabatonShip** [comment]
Can you just remove preview thing? I don't need it

**Comment by dyc3** [comment]
That wouldn't fix anything because we still need the video metadata to play the video, particularly the duration.
