### ISSUE TITLE
Permanent channel creation does not work

### ISSUE THREAD

**Issue by shindouj** [dyc3/opentogethertube#725]
### Current Behavior

When creating a new permanent room, the room created is always temporary. This is reproducible whether the user is logged in or not (note: I use Discord OAuth login).

### Expected Behavior

The created room is permanent.

### Steps To Reproduce

1. Create a permanent room

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

### Anything else?

This is most likely caused by `isTemporary` not being set on room creation in the client (see client/src/components/CreateRoomForm.vue, client/src/util/roomcreator.ts, server/api/room.ts lines 116-118 defaults to a temporary room). This outcome can be confirmed by seeing how logs always confirm that the room created is temporary.

**Comment by dyc3** [comment]
I will fix this tomorrow because i am drunk.

**Comment by dyc3** [comment]
This was a client side issue. When I was refactoring some stuff I forgot to add the option to make the room permanent. Whoops.
