### ISSUE TITLE
Direct links to large mp4s are always timing out

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#740]
### Current Behavior

After inserting a link into the search field, a loading indicator is displayed for 30 seconds, after 30 seconds an error pops up:

![изображение](https://user-images.githubusercontent.com/87234822/192587098-c04d024c-419f-49b8-8c93-0d9d4e9052c8.png)

### Expected Behavior

The video is added to the queue

### Steps To Reproduce

1. Create a temp room
2. Paste https://stream.voidboost.cc/2559c546993406782c1669737514166b:2022092814:YUJOelRrUGNRTlA5eU8xMWlsS0lHcVd2a1VvWHV1Y0szWm8xU0NyTVN0cWw2OW50VmEyNlNhekJ0cXl1TVIyTzhhTzVZZ0xUeEdGUnExQ1dxN3BnU3pHTnJYTFpwdnhKRnQyU2dVTi9pZDQ9/1/7/7/9/2/0/vvgny.mp4 link in search field
3. Wait 30 sec loading indicator

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Sample links:
https://stream.voidboost.cc/2559c546993406782c1669737514166b:2022092814:YUJOelRrUGNRTlA5eU8xMWlsS0lHcVd2a1VvWHV1Y0szWm8xU0NyTVN0cWw2OW50VmEyNlNhekJ0cXl1TVIyTzhhTzVZZ0xUeEdGUnExQ1dxN3BnU3pHTnJYTFpwdnhKRnQyU2dVTi9pZDQ9/1/7/7/9/2/0/vvgny.mp4
https://stream.voidboost.cc/89115d42ffa03935f7fed6b5753e71ac:2022092815:MjNUVUxRSzlBVEErOVhxTm9YUjNNaUprMU0yVU9jWWFMazZzOElzcWZQYkRROXJnOGxjZUY4RTJ6RlZuZWFVeWxxMmRJelBPeCsvMHVmWGRNV1ZSVGc9PQ==/3/6/3/1/7/4/qwukz.mp4
https://stream.voidboost.cc/f4c3a9e4f7da3f4e5372139f5afb381a:2022092815:MjNUVUxRSzlBVEErOVhxTm9YUjNNaUprMU0yVU9jWWFMazZzOElzcWZQYkRROXJnOGxjZUY4RTJ6RlZuZWFVeTIwb0Z5TkNIUm5CeVhQNUlVc0xRZ2c9PQ==/1/0/1/4/0/5/ks5vh.mp4

**Comment by dyc3** [comment]
These are timing out because the file sizes are large.

We have to download the video instead of having ffprobe handle it because ffprobe stopped working on heroku, see #722 . We have to download the entire video because the atom that contains the duration metadata could be at the very end of the file.
