### ISSUE TITLE
Chat not working after creating second and subsequent rooms

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#741]
### Current Behavior

After the second and subsequent room has been created, press T, then type something in field, press ENTER, see nothing in the chat history.

### Expected Behavior

After the room has been created, press T, then type something in field, press ENTER, see your sended message.

### Steps To Reproduce

1. Open  incognito https://opentogethertube.com/
2. Press CREATE ROOM
3. Type something in chat
4. See your message in chat history
5. Press OpenTogetherTube logo
6. Press CREATE ROOM
7. Type something in chat
8. See nothing in the chat history
9. Refresh page
10. Type something in chat
11. See your message in chat history

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Can be fixed by refreshing page

**Comment by dyc3** [comment]
This appears to be fixed now.
