### ISSUE TITLE
cant claim my room

### ISSUE THREAD

**Issue by WtFKilla** [dyc3/opentogethertube#774]
### Current Behavior

created months ago my room https://opentogethertube.com/room/WtFKilla
i already linked with discord before i created this room but cant claim it 

### Expected Behavior

created months ago my room https://opentogethertube.com/room/WtFKilla
i already linked with discord before i created this room but cant claim it 

### Steps To Reproduce

created months ago my room https://opentogethertube.com/room/WtFKilla
i already linked with discord before i created this room but cant claim it 

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
I can't reproduce this locally. Can you open your browser's console and send me the error message when you click "claim room"?

**Comment by WtFKilla** [comment]
Yes tomorrow, i am in bed now.

Carson McManus ***@***.***> schrieb am Mo., 14. Nov. 2022,
02:01:

**Comment by dyc3** [comment]
No rush. Also, you can try 
- logging out and logging back in, and/or
- clearing localstorage by running `window.localStorage.clear()` in the console.

**Comment by WtFKilla** [comment]
btw sorry for the late reply.
[image: image.png]

Am Mo., 14. Nov. 2022 um 02:21 Uhr schrieb Carson McManus <
***@***.***>:

**Comment by dyc3** [comment]
Apparently images don't come through when you send them via email. Can you post the image through github?

And I can just assign your user account as the owner for the room. Is your username just "WtFKilla"?

**Comment by WtFKilla** [comment]
Yeah username is WtFKilla and yes i can Post the Screenshot at github after
my CoD DMZ round

Carson McManus ***@***.***> schrieb am Mi., 16. Nov. 2022,
23:44:

**Comment by WtFKilla** [comment]
![image](https://user-images.githubusercontent.com/9697969/202315003-99a95287-2856-44f1-9f97-a09806a41b8a.png)

Here is the console screenshot

**Comment by WtFKilla** [comment]
and yeah again, Username is WtFKilla and roomname also 
![image](https://user-images.githubusercontent.com/9697969/202315142-d59daf6f-2008-40fb-b77c-a62366cc15e0.png)

**Comment by dyc3** [comment]
Ok, you should be the owner of that room now.
