### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by xorwise** [dyc3/opentogethertube#778]
### Is your feature request related to a problem? Please describe.

I would be really nice, if new videos, that have just been added to a queue, had their names, that users can set while adding,

### Describe the solution you'd like

idk

**Comment by dyc3** [comment]
You're gonna need to elaborate, bud. Are you saying to want to be able to change metadata for a video? Why do you want to do this?

**Comment by dyc3** [comment]
Closing because no response.
