### ISSUE TITLE
Service support: X

### ISSUE THREAD

**Issue by dylanmerte** [dyc3/opentogethertube#789]
### Service Name / Video Format

YouTube Live Video

### About the service

- [ ] Service has a public API
- [ ] Service is a paid/subscription service
- [ ] Service requires an API key
- [X] You can access the service via a browser (mobile app not required)
- [X] Service provides an iframe embed
- [X] Iframe video playback can be controlled via javascript

**Comment by Sebasee009** [comment]
Is already planned in #231
