### ISSUE TITLE
Add sounds for notifications and chats

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#791]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

Play sound when a person enters/leaves a room, when a person sends a message to a chat, when the browser window is inactive/the room tab is inactive. The ability to turn off sounds

### Additional context

It will be useful when you are waiting for another person in the room

**Comment by marthellius** [comment]
I was going to suggest the same. I think this would be a very useful feature to have, specially with regard to chat messages (many times I've missed them because I wasn't looking when they popped up). 

If this get added, there should also be a way to silence the notifications.

**Comment by dyc3** [comment]
I'm a bit wary about adding sounds for join/leave because client reconnects produce the join/leave notifications. Fixable, but requires a bit more work to do without potentially compromising UX.
