### ISSUE TITLE
G Drive link support

### ISSUE THREAD

**Issue by dillfrescott** [dyc3/opentogethertube#792]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

I would like to be able to link an mp4 file from my google drive

**Comment by dyc3** [comment]
This is already implemented, however it is very hacky and buggy and you probably shouldn't use it. The easiest way to watch mp4s right now is to host them on a web server.

**Comment by dillfrescott** [comment]
Ah, gotcha
