### ISSUE TITLE
Buttons on the nav bar are hidden on some window sizes or resolutions

### ISSUE THREAD

**Issue by marthellius** [dyc3/opentogethertube#795]
### Current Behavior

The buttons on the main toolbar are completely hidden when you open OpenTogetherTube on some displays (a FullHD tablet in portrait mode), low resolutions (for example 1024x768) or browser windows narrower than a given width (for example, less than 1000 px). 

The buttons remain completely invisible, even when there is enough space to show them (or at least enough space to show _some_ of them). 

I know that the same buttons can be accessed using the drawer menu, but that's not the point. 

### Expected Behavior

The buttons on the mail toolbar should be always visible, regardless of display resolution or window width. 

If there isn't enough space to show all of them, I think it would be a good idea to show at least the ones that can fit, and perhaps an ellipsis (...) or some icon indicating that there are more of them.

### Steps To Reproduce

This behavior can be reproduced very easily in different ways.

1) Using a FullHD tablet in portrait mode, go to opentogethertube.com (you'll only see the drawer menu icon and the project title on the toolbar)

2) Open a browser window with a width of 1000px or less and go to opentogethertube.com (same result)

3) Open a maximized browser window on a low resolution display (for example 1024x768) and go to opentogethertube.com (same result)

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

I noticed this behavior when I tried to set up a self-hosted version with a customized toolbar having just two buttons: Log In and language selector (modifying client/src/App.vue)

It seemed quite odd that the buttons didn't show on the toolbar, even when there were several hundred pixels of free space to show them. 

At first I thought that somehow this was my fault (because of the modifications I made to the toolbar contents), and I spent a great deal of time trying different approaches without any luck. 

Until I thought to check what happened on the official site, and there I could see that the behavior was the same. 

Finally, I'd like to add something that might be helpful for understanding and debugging this issue:

1) Open a 1000px wide browser window
2) Go to opentogethertube.com (the toolbar buttons are hidden)
3) Now start making the browser window wider. When you reach a specific width (on my computer/display the threshold seems to be 1260px), **the buttons are shown**.
4) Now make the browser window a few pixels narrower (below the threshold in point 3), and **all the buttons are hidden immediately** (even when there is still enough space to show all or most of them)

**Comment by dyc3** [comment]
Thanks for this great bug report! Technically this is intentional behavior, but I will admit it can be improved. I would be open to this change, but I'll need to defer it until #772 is merged.
