### ISSUE TITLE
Add users programmatically (cli tool or api)

### ISSUE THREAD

**Issue by marthellius** [dyc3/opentogethertube#796]
### Is your feature request related to a problem? Please describe.

I run a self-hosted instance of OpenTogetherTube that is used by a group of people that gathers on a IRC channel, where we watch and discuss some movies from time to time. 

Because we only do this from time to time, the OTT instace is volatile. It gets built from scratch using a set of Ansible playbooks when needed, and then it's wiped (it's hosted on a VPS). 

On some occasions the group can be small (around 10 people) but sometimes there can be many more (50+).

To simplify and speed up the process for the users, I register beforehand an account for each of them. And then I just send them the user and password that they'll need to log in. 

When adding the users, I specify for each of them the same nickname that they use on IRC, to have an experience as seamless as possible (the conversation inside the room keeps flowing naturally, because the nicks match those on IRC).

But as you can imagine, it requires a lot of work adding all the accounts manually everytime the instance gets rebuilt.

### Describe the solution you'd like

I would like to be able to add (register) users programmatically, using for example a cli tool or by calling an api.

I run a selft-hosted version of OpenTogetherTube using sqlite, and I've noticed that there's a table called Users in the production.sqlite database. 

However, I don't know how the salt and the hash are generated, and I also don't know if adding a record in that table would be enough for adding a user to the system.

It would be great if a user could be registered by running a cli tool. For example:

`ott-adduser <email> <username> <password>`

Of course the same thing could be accomplished through an api call too. 

### Additional context

I apologize if what I'm asking for already exists. I wasn't able to find it by looking at the project documentation and the past issues.

**Comment by dyc3** [comment]
First of all, thank you very much for the very thorough feature request! 

This is related to #249. I haven't quite gotten around to creating proper API docs.

First, your script will need to grab an auth token from `GET /api/auth/token`. Provide this token in the `Authorization` HTTP header like so:

```
Authorization: Bearer <TOKEN>
```

The HTTP endpoint for registering users is defined here

https://github.com/dyc3/opentogethertube/blob/1f4511e2293e0a8c6da128ee9ff9c12d236937f5/server/usermanager.js#L227

So the endpoint is `POST /api/user/register` with a body following this JSON schema:

```json
{
  "email": "EMAIL",
  "username": "USERNAME",
  "password": "PASSWORD"
}
```

Note that this endpoint is pretty heavily rate limited, and the only way to reset the rate limits is to get redis to delete the keys that track it. I've just made a PR to make the rate limit key prefix configurable via the `RATE_LIMIT_KEY_PREFIX` environment var: #797. The `X-RateLimit-Remaining` HTTP header in responses tells you how much rate limit quota you have remaining.


Another solution might be to back up the production.sqlite on shutdown, and restore it on before startup. I'm going to leave this open to remind me to work on making this easier later:
- There should be a config flag to disable rate limiting,
- and I need to actually whip up some api docs.

**Comment by marthellius** [comment]
Hi, thank you for your valuable feedback on this issue, and for sharing such an amazing project. 

I hadn't thought about backing up the sqlite DB (with the users already created) and restoring it later. I think it's a clever and straighforward solution for the scenario that I've described. 

On the other hand, I'll be looking into the API endpoint for building a more robust and permanent solution. BTW, hitting `/api/auth/token` returns and error, but `/api/auth/grant` seems to provide the required token (I haven't actually tested it yet -- just made some raw calls using curl).

I'll try to write a bash or Go script that iterates over the contents of a CSV file and call the `/register` endpoint for adding each user. I'll take into account the rate limiting, adding a delay between each call (until this can be configured like you explained). 

Thanks again for your comments, which are indeed very useful.

Oh, and a +1 for having some api docs in the future. I think that would be open up endless possibilities for people looking into extending or integrating OpenTogetherTube with other products.

**Comment by dyc3** [comment]
Whoops, you're right, the endpoint is `GET /api/auth/grant`, I've edited my original comment to fix that.

**Comment by marthellius** [comment]
After looking into this and making some tests, I was finally able to add a user programmatically using the `/api/user/register` endpoint .

I'd like to share a small bash script showing a working example. Perhaps it can be useful for someone looking to do the same thing. 

Please note that the script is quite rudimentary (for example, the user credentials are hardcoded). It just shows how to accomplish the task described in the first message of this issue.

```
#!/bin/bash

HOST="localhost:8080"

echo "Getting API auth token ..."
TOKEN=$(curl -s $HOST/api/auth/grant | jq .token | tr -d ['"'])
#echo "Token is: $TOKEN"

cat << EOF > /tmp/user.json
{
  "email": "test@example.com", 
  "username": "test", 
  "password": "testing2023"
}
EOF

echo ""
echo "Adding user through /api/user/register endpoint" 

# Add -v option for debugging the full headers
curl --request POST "$HOST/api/user/register" --header "Authorization: Bearer $TOKEN" \
     --header "Content-Type: application/json" -d @/tmp/user.json
```
