### ISSUE TITLE
Vimeo videos not playing

### ISSUE THREAD

**Issue by mikechans** [dyc3/opentogethertube#813]
### Current Behavior

No video or audio when playing Vimeo links. The playback progress bar is running but there is no video or audio output.

### Expected Behavior

Able to stream Vimeo content.

### Steps To Reproduce

1. Create a room
2. Add a Vimeo video
3. Start playing

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Confirmed. Looks like vimeo changed how their player works.
