### ISSUE TITLE
Fullscreen is broken

### ISSUE THREAD

**Issue by Sebasee009** [dyc3/opentogethertube#820]
### Current Behavior

The problem is that when you go into full screen mode, the size of Video Player is no longer correct.

### Expected Behavior

When you go into full screen mode, the size of Video Player is correct again.

### Steps To Reproduce

1. Create or join room
2. Add Video
3. To full screen mode

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

I also noticed that there is a gap between the video player and the bottom area, when no video or other videos not coming from YouTube are playing.

**Comment by dyc3** [comment]
Could you define what you mean by correct? and are only youtube videos affected or other service's videos?

The gap you're talking about was introduced in #819, it probably should be tweaked a little more.

**Comment by Sebasee009** [comment]
Is the case with all services

**Comment by dyc3** [comment]
Ah yeah I just tried it, I see what you mean.
