### ISSUE TITLE
Direct MP4 sources do not launch automatically

### ISSUE THREAD

**Issue by Scraft02** [dyc3/opentogethertube#827]
### Current Behavior

The mp4 media does not launch automatically on other devices whereas the player of the site is on play. This therefore gives us jerks (due to the syncroinization which works perfectly 👌) but to be able to watch the media we have to right click on the player and click on "Play" so that the player no longer bugs.

### Expected Behavior

This is therefore not a bug but rather an improvement to be made 👍 The reading of the MP4 file should therefore be automatic if the site player is on play.

### Steps To Reproduce

-> Launch an MP4 file on the administrator device
-> Go to the room on another device

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

This improvement could allow better compatibility especially with smartphones/tablets where we cannot right-click to start playback manually and where the site is unusable on this type of file.

**Comment by dyc3** [comment]
I'm having a little trouble understanding what you're asking about, so please correct me if I'm wrong.

In browsers, videos are not allowed to start automatically if they are not muted. They require the user to interact with the page before the video plays. This is something I have no ability to change. The way most sites get around this is to either mute the video, and require the user to unmute it (eg. twitch), get whitelisted (eg. youtube), or require the user to start playback themselves.

**Comment by Scraft02** [comment]
Yes that's right 👍 Damn, then, it is not possible to remedy this problem. It could therefore be beneficial to put a play button to facilitate the intuitiveness of the site and even be able to watch content on mobile devices without suffering this problem. Because there, you have to know how to launch the video with the right click then click on the "play" button of the browser 🤔 (what is not possible on mobiles).
