### ISSUE TITLE
Permanent Room isn't permanent!

### ISSUE THREAD

**Issue by noc2art** [dyc3/opentogethertube#828]
### Current Behavior

I keep creating a permanent room only to never to be able to reach it after I log in although I am a user. What gives???

### Expected Behavior

I expect the permanent room that I created previously to be listed after I log in!

### Steps To Reproduce

1- Create a permanent room, populate it with video links.
2- Log out.
3- Log back in.
4- Good luck trying to find the permanent room. It's nowhere to be found.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
I am not able to reproduce this. From all that I can see, everything is working as expected.

Rooms will not remain listed on the "Browse" page after a certain period of inactivity. You can access permanent rooms that have been unloaded by going directly to the URL for the room: `https://opentogethertube.com/room/<NAME>`, where you replace `<NAME>` with the value you typed into the "name" field when you created the room. There's currently no UI to list all the rooms that you own right now.
