### ISSUE TITLE
Black screen after adding mp4 to queue

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#836]
### Current Behavior

Everything will be fine if you add a video to an empty queue, but if you add another video, a black screen will appear when the first video is skipped

### Expected Behavior

The second video is played with a picture

### Steps To Reproduce

1. Create room
2. Add .mp4 to queue
3. Play .mp4 video
4. Add 2nd .mp4 video to queue
5. Press Skip button
6. Play 2nd video
7. See black screen

### Environment

- [x] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Links examples:
https://draco.stream.voidboost.cc/c69740892f5003cb6d2d4e1a626828d6:2023031515:Z0NyZVRlcml3ZXVJdEtrTW53Q2pUNVhtR3hsUzh4UjFLV0V4UjdRK0NoVk00UDNOWTdyM2g0VWROVXQzSTFYRXEyLzV2OGs4ZDI1ZXR1aXRLZk9NU3NSaWZrbEoxaFdac1N2TXMvcWhhRUk9/7/0/2/8/9/9/ixq0n.mp4
https://zigzag.stream.voidboost.cc/b83f360e1dbcea3d415f697feec9ed5c:2023031515:Z0NyZVRlcml3ZXVJdEtrTW53Q2pUNVhtR3hsUzh4UjFLV0V4UjdRK0NoVk00UDNOWTdyM2g0VWROVXQzSTFYRU9ENFFtS25qbitKbDRVZkRLN0trN1F1aEhiUFM5YXlMcDVGdHF5TmttZlk9/7/0/2/9/0/2/4om9b.mp4

Steps To Reproduce: https://youtu.be/ZOotjnJhud8

**Comment by dyc3** [comment]
Confirmed, I can reproduce this.
