### ISSUE TITLE
Support Subpath hosting

### ISSUE THREAD

**Issue by rexy712** [dyc3/opentogethertube#837]
### Is your feature request related to a problem? Please describe.

I'm already hosting a few services on my server and can't use this project on the root of the domain. I was hoping to host it on a subpath (eg example.com/opentogethertube). It doesn't seem to be supported at this time, making it impossible for me to self host an instance. The other services are running on subpaths without issue, so it would be nice to be able to host this in a similar manner.

### Describe the solution you'd like

Support subpath hosting and having an option in the env file.

### Additional context

I've tried to work around this using nginx `proxy_pass` and `sub_filter`. I got it to work minimally, but it was a hassle to work around some issues this hack caused.

**Comment by dyc3** [comment]
Have you considered hosting it on a subdomain? eg. `ott.example.com`

**Comment by rexy712** [comment]
Yeah if I want to host it that would be how I have to do it. It would just be nice to have the subpath host as an option.  
When I first set up my server, I was using just a ddns address which prevented use of subdomains. Which is why everything for me is running on a subpath.  
I understand if the change isn't worth the effort. I just thought I'd throw the idea out there for consideration.
