### ISSUE TITLE
Locale Selector dropdown is missing

### ISSUE THREAD

**Issue by Scraft02** [dyc3/opentogethertube#838]
### Is your feature request related to a problem? Please describe.

Not due to a problem

### Describe the solution you'd like

Not due to a problem

### Additional context

Add a button to change the language of the site (in the preferences), or even choose the language of your room (in room settings).

**Comment by dyc3** [comment]
This is actually a bug, it should already exist in the site's navigation bar at the top, and the navigation drawer that you can open with the button in the top left on all devices.

**Comment by Scraft02** [comment]
Ok tell me if you have time to solve the problem,I could test from home tomorrow, it's late (soon midnight at home) so I'm going to sleep 😴 Very good end of the day to you and thank you for this extraordinary responsiveness 😁

**Comment by SabatonShip** [comment]
ohh I thought the language was applied automatically based on information about the IP address or browser settings 💀💀💀
