### ISSUE TITLE
Service support: Kickassanimes (aka kaas)

### ISSUE THREAD

**Issue by Kommynct** [dyc3/opentogethertube#888]
### Service Name / Video Format

kickassanimes (kaas)

### URL of homepage

https://kaas.am/

### Sample video URLs

https://kaas.am/dr-stone-b16d/ep-14-83ffe1

### About the service

- [ ] Service has a public API
- [ ] Service is a paid/subscription service
- [ ] Service requires an API key
- [X] You can access the service via a browser (mobile app not required)
- [ ] Service provides an iframe embed
- [ ] Iframe video playback can be controlled via javascript

**Comment by dyc3** [comment]
This website immediately removes all content on the page as soon as you open the dev console. So reverse engineering this is going to be a pain in the ass.

This is what it looks like:
![image](https://github.com/dyc3/opentogethertube/assets/1808807/9cb61d67-2b56-4aee-a2eb-2bf3233fa284)

This also appears to be "kickassanime**s**", which is a different site from "kickassanime" (note the s). I'll update the issue.

**Comment by Kommynct** [comment]
Wow, why would they do that, that is annoying. Thanks for trying!

**Comment by Kommynct** [comment]
Because of that devtools thing? Fair enough, thanks again for trying!
