### ISSUE TITLE
Yarn breaks during install

### ISSUE THREAD

**Issue by bboyles303** [dyc3/opentogethertube#891]
### Current Behavior

While trying to install and doing the yarn install step, I get this:

yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://cdn.cypress.io/beta/npm/12.8.2/linux-x64/retry-dynamic-imports-ed984ef8e1558e8915171384987494bc17b00e27/cypress.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/cnimbus/opentogethertube/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

### Expected Behavior

The install fetches the packages and completes

### Steps To Reproduce

sudo yarn

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Looks like cypress removed this beta version that we were using. I'll update cypress to `12.13.0`.

**Comment by dyc3** [comment]
Also, you probably shouldn't use `sudo`, just `yarn` should suffice.

**Comment by bboyles303** [comment]
> Also, you probably shouldn't use `sudo`, just `yarn` should suffice.

Tried it without as well, still breaks the same way.

**Comment by dyc3** [comment]
Make sure you've checked out the `master` branch and run `git pull`. Can you post logs?

**Comment by bboyles303** [comment]
> Make sure you've checked out the `master` branch and run `git pull`. Can you post logs?

Just pulled and got it working. Got my proxy working. Just gotta daemonize it now.
