### ISSUE TITLE
Default room visibility

### ISSUE THREAD

**Issue by GPery** [dyc3/opentogethertube#895]
### Is your feature request related to a problem? Please describe.

Recently there have been problems with public rooms being flooded by people joining rooms and adding offensive content.

### Describe the solution you'd like

I would want the default room visibility to be Unlisted rather than Public.

**Comment by dyc3** [comment]
I'm open to this. 

This seems like the easiest fix for the spam problem. My metrics suggest people want their rooms unlisted anyway.
