### ISSUE TITLE
Permission denied errors kick clients

### ISSUE THREAD

**Issue by Scraft02** [dyc3/opentogethertube#920]
### Current Behavior

When I play an mp4 file on the player, I find myself on the screen "Disconnected, Something happened, but we don't know what. Please report this as a bug."

### Expected Behavior

Let the video play in the player

### Steps To Reproduce

Paste a link to an online hosted file in mp4 in the "add" window.
Press the play button to launch the content

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by Scraft02** [comment]
It seems that my room is the problem, in the settings I can see that the room needs an owner to modify the settings except that the owner is me normally. I'm recreating a permanent room 👍

**Comment by dyc3** [comment]
I'm confused, that seems completely unrelated. Can you tell me what room names you have so I can look at the logs?

**Comment by Scraft02** [comment]
Here for you : https://opentogethertube.com/room/soireefilm1

**Comment by dyc3** [comment]
Ah, I made a change to how misbehaving clients are handled, and it resulted in clients getting kicked if they try to do something they don't have permissions for. I'll update the issue.
