### ISSUE TITLE
I no longer own my room, and cannot claim it

### ISSUE THREAD

**Issue by Kommynct** [dyc3/opentogethertube#926]
### Current Behavior

![image](https://github.com/dyc3/opentogethertube/assets/13646790/04181930-d05a-4b47-8d91-84028fb2cf51)

My room is no longer owned by me, and clicking claim causes the above error

### Expected Behavior

I should already own the room

### Steps To Reproduce

1. go to my pre-created room
2. click claim room
3. does not work

https://opentogethertube.com/room/commieserver

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by Kommynct** [comment]
Eh, guess I'll just make a new room, deleted it

**Comment by dyc3** [comment]
What's the email, username, or discord id for your account? I can manually change the owner id on the backend.
