### ISSUE TITLE
Automatic exporting and importing of video queue

### ISSUE THREAD

**Issue by Kommynct** [dyc3/opentogethertube#927]
### Is your feature request related to a problem? Please describe.

Sometimes I forget to click export, or my tab unloads, and as a result i've lost the videos in the queue

### Describe the solution you'd like

I'd like it if this was handled server-side, automatically, it'd just have to save the list of videos plaintext and re-import them

**Comment by dyc3** [comment]
Yeah this is kinda what I had in mind originally, but it might take me a bit longer to get this done.
