### ISSUE TITLE
The roles of non-owners are reset after unloading the room from memory?...

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#935]
### Current Behavior

At the moment, if on day 1 you watched something with your admin friend, and you go into the room with him on day 2, he will not have the admin role

### Expected Behavior

Previously, the roles were preserved

### Steps To Reproduce

1. Have a permanent room
2. Log in and let a friend log in too
3. Give the admin role to a friend
4. Enter the room after 1-2 days with a friend
5. Watch as a friend has no role

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This appears to only happen when postgres is the database.
