### ISSUE TITLE
Chat is cleared after adding, skipping a video

### ISSUE THREAD

**Issue by SabatonShip** [dyc3/opentogethertube#936]
### Current Behavior

Chat is cleared after adding, skipping a video

### Expected Behavior

Chat messages are saved and disappear only after the page is reloaded. So it was 2 months ago before the big update

### Steps To Reproduce

1. Create a room
2. Write a message in the chat
3. Add a new video to the queue
4. Watch the message disappear

### Environment

- [x] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

Why are the messages disappearing now? Everything was fine

**Comment by dyc3** [comment]
I literally didn't change anything in that area except update dependencies, so it might be a vue bug.

**Comment by dyc3** [comment]
It looks like the component is being destroyed and recreated whenever the video player changes.
