### ISSUE TITLE
No chat button

### ISSUE THREAD

**Issue by demiurgeQuantified** [dyc3/opentogethertube#942]
### Current Behavior

Since yesterday neither me or my girlfriend have had a chat button in our room. If we press T a chat window of some kind seems to open, but it doesn't have a text box. It doesn't matter what room we try in.

### Expected Behavior

There should be a chat button.

### Steps To Reproduce

1. Create a room
2. Look for the chat button

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

We both use Vivaldi, but Chrome didn't work either.

**Comment by dyc3** [comment]
Yup, I can reproduce this. I'll fix it first thing tomorrow.
