### ISSUE TITLE
Discord Login is broken

### ISSUE THREAD

**Issue by dylanmerte** [dyc3/opentogethertube#944]
### Current Behavior

The option to login with discord is not working, I go’s through the login process but that just directs you back to the home page and your not logged in.

### Expected Behavior

I expect it to login to discord and show that I am logged in from the menu and expect it to bring me back to the permanent page I setup but it doesn’t.

### Steps To Reproduce

Try logging in with the discord option.

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Whoops, look like this slipped through the cracks. I can reproduce this, I'll fix it tomorrow.

**Comment by dyc3** [comment]
Looks like this broke in commit 9fa278a9236dfa91f3cb3ca5a8ff460d11bfadf6, which is #917
