### ISSUE TITLE
Mixer support

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#98]
Requires #246 

Support for watching mixer livestreams

React with 👍 if you are interested in this

**Comment by dyc3** [comment]
https://dev.mixer.com/rest/index.html

**Comment by Butt4cak3** [comment]
From the Mixer website:
> As of July 22, the Mixer service has closed.

I'm pretty sure you can close this.

**Comment by dyc3** [comment]
Yeah, good catch.
